In [ ]:
data1 = [
   ["List all tools used in innovations created after 2022.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate > '2022-12-31';"],
   ["List all tools used in innovations created after 2023.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate > '2023-12-31';"],
   ["What is the total number of jobs applied by innovations created by 'John Doe'?", "SELECT SUM(Jidouka.TotalJobApplied) FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%John Doe%');"],
   ["What is the total number of jobs applied by innovations created by 'Nguyễn Văn Hải'?", "SELECT SUM(Jidouka.TotalJobApplied) FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%Nguyễn Văn Hải%');"],
   ["What is the total number of jobs applied by innovations created by 'Ngô Thì Nhậm'?", "SELECT SUM(Jidouka.TotalJobApplied) FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%Ngô Thì Nhậm%');"],
   ["List all tools used in innovations created after 2010.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate > '2010-12-31';"],
   ["List all tools used in innovations created before 2010.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate < '2010-01-01';"],
   ["What are the most used tools?","SELECT Tool.ToolName, COUNT(*) AS UsageCount FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId GROUP BY Tool.ToolName ORDER BY UsageCount DESC;"],
   ["What are the least used tools?","SELECT Tool.ToolName, COUNT(*) AS UsageCount FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId GROUP BY Tool.ToolName ORDER BY UsageCount ASC;"],
   ["What are the details of innovations created on 2023-01-01?","SELECT ImprovementName, Description FROM Jidouka WHERE DateCreate LIKE LOWER('%2023-01-01%');"],
   ["What are the details of innovations created on 2024-01-01?","SELECT ImprovementName, Description FROM Jidouka WHERE DateCreate LIKE LOWER('%2024-01-01%');"],
   ["Detail of information created on the first day of 2024","SELECT ImprovementName, Description FROM Jidouka WHERE DateCreate LIKE LOWER('%2024-01-01%');"],
   ["List all jobs that apply the innovation 'Automation X'.","SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.ImprovementName LIKE LOWER('%Automation X%');"],
   ["List all jobs that apply the innovation Automation Y.","SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.ImprovementName LIKE LOWER('%Automation Y%');"],
   ["List all improvements made by the design center 'Electronics'.", "SELECT Jidouka.ImprovementName FROM Jidouka JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%Electronics%');" ],
   ["List all tools used for innovations created before 2023-01-01.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate < '2023-01-01';"],
   ["Which innovations are associated with the author named 'John Doe'?","SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%John Doe%');"],
   ["Find the total number of jobs linked to innovations by 'Design Center A'.","SELECT COUNT(DISTINCT Job.JobId) AS TotalJobs FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%Design Center A%');"],
   ["Which teams worked on innovations related to 'Machine Parts'?","SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId WHERE LOWER(Jidouka.ProductApply) LIKE '%machine parts%';"],
   ["Which innovations were created by authors who have worked on tools with the word 'analysis' in their description?", "SELECT DISTINCT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorId IN (SELECT DISTINCT Jidouka.AuthorId FROM Jidouka JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE LOWER(Tool.ToolDescription) LIKE '%analysis%');"],
   ["List all innovations created by employees of the 'Engineering Department'.", "SELECT Jidouka.ImprovementName FROM Jidouka JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%Engineering Department%');"],
   ["List all authors who have created more than 5 innovations.", "SELECT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId GROUP BY Author.AuthorName HAVING COUNT(Jidouka.JidoukaId) > 5;"],
   ["Find innovations created by authors from the 'Manufacturing' department.", "SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId JOIN Department ON Author.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%Manufacturing%');"],
   ["Find all innovations in the 'R&D' department that applied more than 8 jobs.", "SELECT Jidouka.ImprovementName FROM Jidouka JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%R&D%') AND Jidouka.TotalJobApplied > 8;"],
   ["List all authors who created more than 3 innovations.", "SELECT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId GROUP BY Author.AuthorName HAVING COUNT(Jidouka.JidoukaId) > 3;"],
   ["Which departments have saved more than 500 hours through innovations?","SELECT DISTINCT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE TotalTimeSaved > 500;"],
   ["List all authors who created innovations in 2022.", "SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE YEAR(DateCreate) = 2022;"],
   ["Which departments had innovations with more than 10 jobs applied?","SELECT DISTINCT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE TotalJobApplied > 10;"],
   ["Which department has innovations involving the maximum number of tools?","SELECT Department.DepartmentName, COUNT(DISTINCT JidoukaTool.ToolId) AS ToolCount FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId GROUP BY Department.DepartmentName ORDER BY ToolCount DESC LIMIT 1;"],
   ["Find the oldest innovation for each department.", "SELECT Department.DepartmentName, MIN(Jidouka.DateCreate) AS OldestInnovationDate FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId GROUP BY Department.DepartmentName;"],
   ["What are the names of authors who worked on innovations with the keyword 'robotics'?","SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE LOWER(Jidouka.Description) LIKE '%robotics%';"],
   ["Which authors created innovations in the last five years?","SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE DateCreate >= DATE_SUB(CURDATE(), INTERVAL 5 YEAR);"],
   ["Những cải tiến nào có ngày tạo trùng với ngày tạo của tác giả?","SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Jidouka.DateCreate = Author.DateCreate;"],
   ["Liệt kê tất cả các cải tiến được tạo bởi tác giả có tên là 'Nguyễn Văn A'","SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%Nguyễn Văn A%');"],
   ["Những cải tiến được thực hiện bởi nhân viên 'Nguyễn Văn A' thuộc nhóm 'Team Beta' có ngày ra mắt trong khoảng từ tháng 1 đến tháng 3 năm 2024 là gì?","SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId JOIN GroupDC ON Jidouka.GroupDCId = GroupDC.GroupDCId WHERE Author.AuthorName LIKE LOWER('%Nguyễn Văn A%') AND GroupDC.GroupDCName LIKE LOWER('%Team Beta%') AND Jidouka.DateCreate BETWEEN '2024-01-01' AND '2024-03-31';"],
   ["List all tools used in innovations created after 2022.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate > '2022-12-31';"],
   ["List all tools used in innovations created after 2023.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate > '2023-12-31';"],
   ["What is the total number of jobs applied by innovations created by 'John Doe'?", "SELECT SUM(Jidouka.TotalJobApplied) FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%John Doe%');"],
   ["What is the total number of jobs applied by innovations created by 'Nguyễn Văn Hải'?", "SELECT SUM(Jidouka.TotalJobApplied) FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%Nguyễn Văn Hải%');"],
   ["What is the total number of jobs applied by innovations created by 'Ngô Thì Nhậm'?", "SELECT SUM(Jidouka.TotalJobApplied) FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%Ngô Thì Nhậm%');"],
   ["List all tools used in innovations created after 2010.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate > '2010-12-31';"],
   ["List all tools used in innovations created before 2010.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate < '2010-01-01';"],
   ["What are the most used tools?","SELECT Tool.ToolName, COUNT(*) AS UsageCount FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId GROUP BY Tool.ToolName ORDER BY UsageCount DESC;"],
   ["What are the least used tools?","SELECT Tool.ToolName, COUNT(*) AS UsageCount FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId GROUP BY Tool.ToolName ORDER BY UsageCount ASC;"],
   ["What are the details of innovations created on 2023-01-01?","SELECT ImprovementName, Description FROM Jidouka WHERE DateCreate LIKE LOWER('%2023-01-01%');"],
   ["What are the details of innovations created on 2024-01-01?","SELECT ImprovementName, Description FROM Jidouka WHERE DateCreate LIKE LOWER('%2024-01-01%');"],
   ["Detail of information created on the first day of 2024","SELECT ImprovementName, Description FROM Jidouka WHERE DateCreate LIKE LOWER('%2024-01-01%');"],
   ["List all jobs that apply the innovation 'Automation X'.","SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.ImprovementName LIKE LOWER('%Automation X%');"],
   ["List all jobs that apply the innovation Automation Y.","SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.ImprovementName LIKE LOWER('%Automation Y%');"],
   ["List all improvements made by the design center 'Electronics'.", "SELECT Jidouka.ImprovementName FROM Jidouka JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%Electronics%');" ],
   ["List all tools used for innovations created before 2023-01-01.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate < '2023-01-01';"],
   ["Which innovations are associated with the author named 'John Doe'?","SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%John Doe%');"],
   ["Find the total number of jobs linked to innovations by 'Design Center A'.","SELECT COUNT(DISTINCT Job.JobId) AS TotalJobs FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%Design Center A%');"],
   ["Which teams worked on innovations related to 'Machine Parts'?","SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId WHERE LOWER(Jidouka.ProductApply) LIKE '%machine parts%';"],
   ["Which innovations were created by authors who have worked on tools with the word 'analysis' in their description?", "SELECT DISTINCT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorId IN (SELECT DISTINCT Jidouka.AuthorId FROM Jidouka JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE LOWER(Tool.ToolDescription) LIKE '%analysis%');"],
   ["List all innovations created by employees of the 'Engineering Department'.", "SELECT Jidouka.ImprovementName FROM Jidouka JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%Engineering Department%');"],
   ["List all authors who have created more than 5 innovations.", "SELECT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId GROUP BY Author.AuthorName HAVING COUNT(Jidouka.JidoukaId) > 5;"],
   ["Find innovations created by authors from the 'Manufacturing' department.", "SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId JOIN Department ON Author.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%Manufacturing%');"],
   ["Find all innovations in the 'R&D' department that applied more than 8 jobs.", "SELECT Jidouka.ImprovementName FROM Jidouka JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%R&D%') AND Jidouka.TotalJobApplied > 8;"],
   ["List all authors who created more than 3 innovations.", "SELECT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId GROUP BY Author.AuthorName HAVING COUNT(Jidouka.JidoukaId) > 3;"],
   ["Which departments have saved more than 500 hours through innovations?","SELECT DISTINCT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE TotalTimeSaved > 500;"],
   ["List all authors who created innovations in 2022.", "SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE YEAR(DateCreate) = 2022;"],
   ["Which departments had innovations with more than 10 jobs applied?","SELECT DISTINCT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE TotalJobApplied > 10;"],
   ["Which department has innovations involving the maximum number of tools?","SELECT Department.DepartmentName, COUNT(DISTINCT JidoukaTool.ToolId) AS ToolCount FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId GROUP BY Department.DepartmentName ORDER BY ToolCount DESC LIMIT 1;"],
   ["Find the oldest innovation for each department.", "SELECT Department.DepartmentName, MIN(Jidouka.DateCreate) AS OldestInnovationDate FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId GROUP BY Department.DepartmentName;"],
   ["What are the names of authors who worked on innovations with the keyword 'robotics'?","SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE LOWER(Jidouka.Description) LIKE '%robotics%';"],
   ["Which authors created innovations in the last five years?","SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE DateCreate >= DATE_SUB(CURDATE(), INTERVAL 5 YEAR);"],
   ["Những cải tiến nào có ngày tạo trùng với ngày tạo của tác giả?","SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Jidouka.DateCreate = Author.DateCreate;"],
   ["Liệt kê tất cả các cải tiến được tạo bởi tác giả có tên là 'Nguyễn Văn A'","SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%Nguyễn Văn A%');"],
   ["Những cải tiến được thực hiện bởi nhân viên 'Nguyễn Văn A' thuộc nhóm 'Team Beta' có ngày ra mắt trong khoảng từ tháng 1 đến tháng 3 năm 2024 là gì?","SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId JOIN GroupDC ON Jidouka.GroupDCId = GroupDC.GroupDCId WHERE Author.AuthorName LIKE LOWER('%Nguyễn Văn A%') AND GroupDC.GroupDCName LIKE LOWER('%Team Beta%') AND Jidouka.DateCreate BETWEEN '2024-01-01' AND '2024-03-31';"],
   ["List all tools used in innovations created after 2022.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate > '2022-12-31';"],
   ["List all tools used in innovations created after 2023.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate > '2023-12-31';"],
   ["What is the total number of jobs applied by innovations created by 'John Doe'?", "SELECT SUM(Jidouka.TotalJobApplied) FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%John Doe%');"],
   ["What is the total number of jobs applied by innovations created by 'Nguyễn Văn Hải'?", "SELECT SUM(Jidouka.TotalJobApplied) FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%Nguyễn Văn Hải%');"],
   ["What is the total number of jobs applied by innovations created by 'Ngô Thì Nhậm'?", "SELECT SUM(Jidouka.TotalJobApplied) FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%Ngô Thì Nhậm%');"],
   ["List all tools used in innovations created after 2010.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate > '2010-12-31';"],
   ["List all tools used in innovations created before 2010.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate < '2010-01-01';"],
   ["What are the most used tools?","SELECT Tool.ToolName, COUNT(*) AS UsageCount FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId GROUP BY Tool.ToolName ORDER BY UsageCount DESC;"],
   ["What are the least used tools?","SELECT Tool.ToolName, COUNT(*) AS UsageCount FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId GROUP BY Tool.ToolName ORDER BY UsageCount ASC;"],
   ["What are the details of innovations created on 2023-01-01?","SELECT ImprovementName, Description FROM Jidouka WHERE DateCreate LIKE LOWER('%2023-01-01%');"],
   ["What are the details of innovations created on 2024-01-01?","SELECT ImprovementName, Description FROM Jidouka WHERE DateCreate LIKE LOWER('%2024-01-01%');"],
   ["Detail of information created on the first day of 2024","SELECT ImprovementName, Description FROM Jidouka WHERE DateCreate LIKE LOWER('%2024-01-01%');"],
   ["List all jobs that apply the innovation 'Automation X'.","SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.ImprovementName LIKE LOWER('%Automation X%');"],
   ["List all jobs that apply the innovation Automation Y.","SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.ImprovementName LIKE LOWER('%Automation Y%');"],
   ["List all improvements made by the design center 'Electronics'.", "SELECT Jidouka.ImprovementName FROM Jidouka JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%Electronics%');" ],
   ["List all tools used for innovations created before 2023-01-01.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate < '2023-01-01';"],
   ["Which innovations are associated with the author named 'John Doe'?","SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%John Doe%');"],
   ["Find the total number of jobs linked to innovations by 'Design Center A'.","SELECT COUNT(DISTINCT Job.JobId) AS TotalJobs FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%Design Center A%');"],
   ["Which teams worked on innovations related to 'Machine Parts'?","SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId WHERE LOWER(Jidouka.ProductApply) LIKE '%machine parts%';"],
   ["Which innovations were created by authors who have worked on tools with the word 'analysis' in their description?", "SELECT DISTINCT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorId IN (SELECT DISTINCT Jidouka.AuthorId FROM Jidouka JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE LOWER(Tool.ToolDescription) LIKE '%analysis%');"],
   ["List all innovations created by employees of the 'Engineering Department'.", "SELECT Jidouka.ImprovementName FROM Jidouka JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%Engineering Department%');"],
   ["List all authors who have created more than 5 innovations.", "SELECT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId GROUP BY Author.AuthorName HAVING COUNT(Jidouka.JidoukaId) > 5;"],
   ["Find innovations created by authors from the 'Manufacturing' department.", "SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId JOIN Department ON Author.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%Manufacturing%');"],
   ["Find all innovations in the 'R&D' department that applied more than 8 jobs.", "SELECT Jidouka.ImprovementName FROM Jidouka JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%R&D%') AND Jidouka.TotalJobApplied > 8;"],
   ["List all authors who created more than 3 innovations.", "SELECT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId GROUP BY Author.AuthorName HAVING COUNT(Jidouka.JidoukaId) > 3;"],
   ["Which departments have saved more than 500 hours through innovations?","SELECT DISTINCT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE TotalTimeSaved > 500;"],
   ["List all authors who created innovations in 2022.", "SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE YEAR(DateCreate) = 2022;"],
   ["Which departments had innovations with more than 10 jobs applied?","SELECT DISTINCT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE TotalJobApplied > 10;"],
   ["Which department has innovations involving the maximum number of tools?","SELECT Department.DepartmentName, COUNT(DISTINCT JidoukaTool.ToolId) AS ToolCount FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId GROUP BY Department.DepartmentName ORDER BY ToolCount DESC LIMIT 1;"],
   ["Find the oldest innovation for each department.", "SELECT Department.DepartmentName, MIN(Jidouka.DateCreate) AS OldestInnovationDate FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId GROUP BY Department.DepartmentName;"],
   ["What are the names of authors who worked on innovations with the keyword 'robotics'?","SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE LOWER(Jidouka.Description) LIKE '%robotics%';"],
   ["Which authors created innovations in the last five years?","SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE DateCreate >= DATE_SUB(CURDATE(), INTERVAL 5 YEAR);"],
   ["Những cải tiến nào có ngày tạo trùng với ngày tạo của tác giả?","SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Jidouka.DateCreate = Author.DateCreate;"],
   ["Liệt kê tất cả các cải tiến được tạo bởi tác giả có tên là 'Nguyễn Văn A'","SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%Nguyễn Văn A%');"],
   ["Những cải tiến được thực hiện bởi nhân viên 'Nguyễn Văn A' thuộc nhóm 'Team Beta' có ngày ra mắt trong khoảng từ tháng 1 đến tháng 3 năm 2024 là gì?","SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId JOIN GroupDC ON Jidouka.GroupDCId = GroupDC.GroupDCId WHERE Author.AuthorName LIKE LOWER('%Nguyễn Văn A%') AND GroupDC.GroupDCName LIKE LOWER('%Team Beta%') AND Jidouka.DateCreate BETWEEN '2024-01-01' AND '2024-03-31';"],
   ["List all tools used in innovations created after 2022.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate > '2022-12-31';"],
   ["List all tools used in innovations created after 2023.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate > '2023-12-31';"],
   ["What is the total number of jobs applied by innovations created by 'John Doe'?", "SELECT SUM(Jidouka.TotalJobApplied) FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%John Doe%');"],
   ["What is the total number of jobs applied by innovations created by 'Nguyễn Văn Hải'?", "SELECT SUM(Jidouka.TotalJobApplied) FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%Nguyễn Văn Hải%');"],
   ["What is the total number of jobs applied by innovations created by 'Ngô Thì Nhậm'?", "SELECT SUM(Jidouka.TotalJobApplied) FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%Ngô Thì Nhậm%');"],
   ["List all tools used in innovations created after 2010.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate > '2010-12-31';"],
   ["List all tools used in innovations created before 2010.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate < '2010-01-01';"],
   ["What are the most used tools?","SELECT Tool.ToolName, COUNT(*) AS UsageCount FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId GROUP BY Tool.ToolName ORDER BY UsageCount DESC;"],
   ["What are the least used tools?","SELECT Tool.ToolName, COUNT(*) AS UsageCount FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId GROUP BY Tool.ToolName ORDER BY UsageCount ASC;"],
   ["What are the details of innovations created on 2023-01-01?","SELECT ImprovementName, Description FROM Jidouka WHERE DateCreate LIKE LOWER('%2023-01-01%');"],
   ["What are the details of innovations created on 2024-01-01?","SELECT ImprovementName, Description FROM Jidouka WHERE DateCreate LIKE LOWER('%2024-01-01%');"],
   ["Detail of information created on the first day of 2024","SELECT ImprovementName, Description FROM Jidouka WHERE DateCreate LIKE LOWER('%2024-01-01%');"],
   ["List all jobs that apply the innovation 'Automation X'.","SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.ImprovementName LIKE LOWER('%Automation X%');"],
   ["List all jobs that apply the innovation Automation Y.","SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.ImprovementName LIKE LOWER('%Automation Y%');"],
   ["List all improvements made by the design center 'Electronics'.", "SELECT Jidouka.ImprovementName FROM Jidouka JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%Electronics%');" ],
   ["List all tools used for innovations created before 2023-01-01.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate < '2023-01-01';"],
   ["Which innovations are associated with the author named 'John Doe'?","SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%John Doe%');"],
   ["Find the total number of jobs linked to innovations by 'Design Center A'.","SELECT COUNT(DISTINCT Job.JobId) AS TotalJobs FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%Design Center A%');"],
   ["Which teams worked on innovations related to 'Machine Parts'?","SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId WHERE LOWER(Jidouka.ProductApply) LIKE '%machine parts%';"],
   ["Which innovations were created by authors who have worked on tools with the word 'analysis' in their description?", "SELECT DISTINCT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorId IN (SELECT DISTINCT Jidouka.AuthorId FROM Jidouka JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE LOWER(Tool.ToolDescription) LIKE '%analysis%');"],
   ["List all innovations created by employees of the 'Engineering Department'.", "SELECT Jidouka.ImprovementName FROM Jidouka JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%Engineering Department%');"],
   ["List all authors who have created more than 5 innovations.", "SELECT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId GROUP BY Author.AuthorName HAVING COUNT(Jidouka.JidoukaId) > 5;"],
   ["Find innovations created by authors from the 'Manufacturing' department.", "SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId JOIN Department ON Author.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%Manufacturing%');"],
   ["Find all innovations in the 'R&D' department that applied more than 8 jobs.", "SELECT Jidouka.ImprovementName FROM Jidouka JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%R&D%') AND Jidouka.TotalJobApplied > 8;"],
   ["List all authors who created more than 3 innovations.", "SELECT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId GROUP BY Author.AuthorName HAVING COUNT(Jidouka.JidoukaId) > 3;"],
   ["Which departments have saved more than 500 hours through innovations?","SELECT DISTINCT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE TotalTimeSaved > 500;"],
   ["List all authors who created innovations in 2022.", "SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE YEAR(DateCreate) = 2022;"],
   ["Which departments had innovations with more than 10 jobs applied?","SELECT DISTINCT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE TotalJobApplied > 10;"],
   ["Which department has innovations involving the maximum number of tools?","SELECT Department.DepartmentName, COUNT(DISTINCT JidoukaTool.ToolId) AS ToolCount FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId GROUP BY Department.DepartmentName ORDER BY ToolCount DESC LIMIT 1;"],
   ["Find the oldest innovation for each department.", "SELECT Department.DepartmentName, MIN(Jidouka.DateCreate) AS OldestInnovationDate FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId GROUP BY Department.DepartmentName;"],
   ["What are the names of authors who worked on innovations with the keyword 'robotics'?","SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE LOWER(Jidouka.Description) LIKE '%robotics%';"],
   ["Which authors created innovations in the last five years?","SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE DateCreate >= DATE_SUB(CURDATE(), INTERVAL 5 YEAR);"],
   ["Những cải tiến nào có ngày tạo trùng với ngày tạo của tác giả?","SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Jidouka.DateCreate = Author.DateCreate;"],
   ["Liệt kê tất cả các cải tiến được tạo bởi tác giả có tên là 'Nguyễn Văn A'","SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%Nguyễn Văn A%');"],
   ["Những cải tiến được thực hiện bởi nhân viên 'Nguyễn Văn A' thuộc nhóm 'Team Beta' có ngày ra mắt trong khoảng từ tháng 1 đến tháng 3 năm 2024 là gì?","SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId JOIN GroupDC ON Jidouka.GroupDCId = GroupDC.GroupDCId WHERE Author.AuthorName LIKE LOWER('%Nguyễn Văn A%') AND GroupDC.GroupDCName LIKE LOWER('%Team Beta%') AND Jidouka.DateCreate BETWEEN '2024-01-01' AND '2024-03-31';"],
   ["List all tools used in innovations created after 2022.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate > '2022-12-31';"],
   ["List all tools used in innovations created after 2023.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate > '2023-12-31';"],
   ["What is the total number of jobs applied by innovations created by 'John Doe'?", "SELECT SUM(Jidouka.TotalJobApplied) FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%John Doe%');"],
   ["What is the total number of jobs applied by innovations created by 'Nguyễn Văn Hải'?", "SELECT SUM(Jidouka.TotalJobApplied) FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%Nguyễn Văn Hải%');"],
   ["What is the total number of jobs applied by innovations created by 'Ngô Thì Nhậm'?", "SELECT SUM(Jidouka.TotalJobApplied) FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%Ngô Thì Nhậm%');"],
   ["List all tools used in innovations created after 2010.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate > '2010-12-31';"],
   ["List all tools used in innovations created before 2010.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate < '2010-01-01';"],
   ["What are the most used tools?","SELECT Tool.ToolName, COUNT(*) AS UsageCount FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId GROUP BY Tool.ToolName ORDER BY UsageCount DESC;"],
   ["What are the least used tools?","SELECT Tool.ToolName, COUNT(*) AS UsageCount FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId GROUP BY Tool.ToolName ORDER BY UsageCount ASC;"],
   ["What are the details of innovations created on 2023-01-01?","SELECT ImprovementName, Description FROM Jidouka WHERE DateCreate LIKE LOWER('%2023-01-01%');"],
   ["What are the details of innovations created on 2024-01-01?","SELECT ImprovementName, Description FROM Jidouka WHERE DateCreate LIKE LOWER('%2024-01-01%');"],
   ["Detail of information created on the first day of 2024","SELECT ImprovementName, Description FROM Jidouka WHERE DateCreate LIKE LOWER('%2024-01-01%');"],
   ["List all jobs that apply the innovation 'Automation X'.","SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.ImprovementName LIKE LOWER('%Automation X%');"],
   ["List all jobs that apply the innovation Automation Y.","SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.ImprovementName LIKE LOWER('%Automation Y%');"],
   ["List all improvements made by the design center 'Electronics'.", "SELECT Jidouka.ImprovementName FROM Jidouka JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%Electronics%');" ],
   ["List all tools used for innovations created before 2023-01-01.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate < '2023-01-01';"],
   ["Which innovations are associated with the author named 'John Doe'?","SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%John Doe%');"],
   ["Find the total number of jobs linked to innovations by 'Design Center A'.","SELECT COUNT(DISTINCT Job.JobId) AS TotalJobs FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%Design Center A%');"],
   ["Which teams worked on innovations related to 'Machine Parts'?","SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId WHERE LOWER(Jidouka.ProductApply) LIKE '%machine parts%';"],
   ["Which innovations were created by authors who have worked on tools with the word 'analysis' in their description?", "SELECT DISTINCT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorId IN (SELECT DISTINCT Jidouka.AuthorId FROM Jidouka JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE LOWER(Tool.ToolDescription) LIKE '%analysis%');"],
   ["List all innovations created by employees of the 'Engineering Department'.", "SELECT Jidouka.ImprovementName FROM Jidouka JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%Engineering Department%');"],
   ["List all authors who have created more than 5 innovations.", "SELECT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId GROUP BY Author.AuthorName HAVING COUNT(Jidouka.JidoukaId) > 5;"],
   ["Find innovations created by authors from the 'Manufacturing' department.", "SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId JOIN Department ON Author.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%Manufacturing%');"],
   ["Find all innovations in the 'R&D' department that applied more than 8 jobs.", "SELECT Jidouka.ImprovementName FROM Jidouka JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%R&D%') AND Jidouka.TotalJobApplied > 8;"],
   ["List all authors who created more than 3 innovations.", "SELECT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId GROUP BY Author.AuthorName HAVING COUNT(Jidouka.JidoukaId) > 3;"],
   ["Which departments have saved more than 500 hours through innovations?","SELECT DISTINCT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE TotalTimeSaved > 500;"],
   ["List all authors who created innovations in 2022.", "SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE YEAR(DateCreate) = 2022;"],
   ["Which departments had innovations with more than 10 jobs applied?","SELECT DISTINCT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE TotalJobApplied > 10;"],
   ["Which department has innovations involving the maximum number of tools?","SELECT Department.DepartmentName, COUNT(DISTINCT JidoukaTool.ToolId) AS ToolCount FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId GROUP BY Department.DepartmentName ORDER BY ToolCount DESC LIMIT 1;"],
   ["Find the oldest innovation for each department.", "SELECT Department.DepartmentName, MIN(Jidouka.DateCreate) AS OldestInnovationDate FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId GROUP BY Department.DepartmentName;"],
   ["What are the names of authors who worked on innovations with the keyword 'robotics'?","SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE LOWER(Jidouka.Description) LIKE '%robotics%';"],
   ["Which authors created innovations in the last five years?","SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE DateCreate >= DATE_SUB(CURDATE(), INTERVAL 5 YEAR);"],
   ["Những cải tiến nào có ngày tạo trùng với ngày tạo của tác giả?","SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Jidouka.DateCreate = Author.DateCreate;"],
   ["Liệt kê tất cả các cải tiến được tạo bởi tác giả có tên là 'Nguyễn Văn A'","SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%Nguyễn Văn A%');"],
   ["Những cải tiến được thực hiện bởi nhân viên 'Nguyễn Văn A' thuộc nhóm 'Team Beta' có ngày ra mắt trong khoảng từ tháng 1 đến tháng 3 năm 2024 là gì?","SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId JOIN GroupDC ON Jidouka.GroupDCId = GroupDC.GroupDCId WHERE Author.AuthorName LIKE LOWER('%Nguyễn Văn A%') AND GroupDC.GroupDCName LIKE LOWER('%Team Beta%') AND Jidouka.DateCreate BETWEEN '2024-01-01' AND '2024-03-31';"],
   ["List all tools used in innovations created after 2022.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate > '2022-12-31';"],
   ["List all tools used in innovations created after 2023.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate > '2023-12-31';"],
   ["What is the total number of jobs applied by innovations created by 'John Doe'?", "SELECT SUM(Jidouka.TotalJobApplied) FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%John Doe%');"],
   ["What is the total number of jobs applied by innovations created by 'Nguyễn Văn Hải'?", "SELECT SUM(Jidouka.TotalJobApplied) FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%Nguyễn Văn Hải%');"],
   ["What is the total number of jobs applied by innovations created by 'Ngô Thì Nhậm'?", "SELECT SUM(Jidouka.TotalJobApplied) FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%Ngô Thì Nhậm%');"],
   ["List all tools used in innovations created after 2010.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate > '2010-12-31';"],
   ["List all tools used in innovations created before 2010.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate < '2010-01-01';"],
   ["What are the most used tools?","SELECT Tool.ToolName, COUNT(*) AS UsageCount FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId GROUP BY Tool.ToolName ORDER BY UsageCount DESC;"],
   ["What are the least used tools?","SELECT Tool.ToolName, COUNT(*) AS UsageCount FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId GROUP BY Tool.ToolName ORDER BY UsageCount ASC;"],
   ["What are the details of innovations created on 2023-01-01?","SELECT ImprovementName, Description FROM Jidouka WHERE DateCreate LIKE LOWER('%2023-01-01%');"],
   ["What are the details of innovations created on 2024-01-01?","SELECT ImprovementName, Description FROM Jidouka WHERE DateCreate LIKE LOWER('%2024-01-01%');"],
   ["Detail of information created on the first day of 2024","SELECT ImprovementName, Description FROM Jidouka WHERE DateCreate LIKE LOWER('%2024-01-01%');"],
   ["List all jobs that apply the innovation 'Automation X'.","SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.ImprovementName LIKE LOWER('%Automation X%');"],
   ["List all jobs that apply the innovation Automation Y.","SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.ImprovementName LIKE LOWER('%Automation Y%');"],
   ["List all improvements made by the design center 'Electronics'.", "SELECT Jidouka.ImprovementName FROM Jidouka JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%Electronics%');" ],
   ["List all tools used for innovations created before 2023-01-01.", "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate < '2023-01-01';"],
   ["Which innovations are associated with the author named 'John Doe'?","SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%John Doe%');"],
   ["Find the total number of jobs linked to innovations by 'Design Center A'.","SELECT COUNT(DISTINCT Job.JobId) AS TotalJobs FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%Design Center A%');"],
   ["Which teams worked on innovations related to 'Machine Parts'?","SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId WHERE LOWER(Jidouka.ProductApply) LIKE '%machine parts%';"],
   ["Which innovations were created by authors who have worked on tools with the word 'analysis' in their description?", "SELECT DISTINCT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorId IN (SELECT DISTINCT Jidouka.AuthorId FROM Jidouka JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE LOWER(Tool.ToolDescription) LIKE '%analysis%');"],
   ["List all innovations created by employees of the 'Engineering Department'.", "SELECT Jidouka.ImprovementName FROM Jidouka JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%Engineering Department%');"],
   ["List all authors who have created more than 5 innovations.", "SELECT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId GROUP BY Author.AuthorName HAVING COUNT(Jidouka.JidoukaId) > 5;"],
   ["Find innovations created by authors from the 'Manufacturing' department.", "SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId JOIN Department ON Author.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%Manufacturing%');"],
   ["Find all innovations in the 'R&D' department that applied more than 8 jobs.", "SELECT Jidouka.ImprovementName FROM Jidouka JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%R&D%') AND Jidouka.TotalJobApplied > 8;"],
   ["List all authors who created more than 3 innovations.", "SELECT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId GROUP BY Author.AuthorName HAVING COUNT(Jidouka.JidoukaId) > 3;"],
   ["Which departments have saved more than 500 hours through innovations?","SELECT DISTINCT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE TotalTimeSaved > 500;"],
   ["List all authors who created innovations in 2022.", "SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE YEAR(DateCreate) = 2022;"],
   ["Which departments had innovations with more than 10 jobs applied?","SELECT DISTINCT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE TotalJobApplied > 10;"],
   ["Which department has innovations involving the maximum number of tools?","SELECT Department.DepartmentName, COUNT(DISTINCT JidoukaTool.ToolId) AS ToolCount FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId GROUP BY Department.DepartmentName ORDER BY ToolCount DESC LIMIT 1;"],
   ["Find the oldest innovation for each department.", "SELECT Department.DepartmentName, MIN(Jidouka.DateCreate) AS OldestInnovationDate FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId GROUP BY Department.DepartmentName;"],
   ["What are the names of authors who worked on innovations with the keyword 'robotics'?","SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE LOWER(Jidouka.Description) LIKE '%robotics%';"],
   ["Which authors created innovations in the last five years?","SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE DateCreate >= DATE_SUB(CURDATE(), INTERVAL 5 YEAR);"],
   ["Những cải tiến nào có ngày tạo trùng với ngày tạo của tác giả?","SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Jidouka.DateCreate = Author.DateCreate;"],
   ["Liệt kê tất cả các cải tiến được tạo bởi tác giả có tên là 'Nguyễn Văn A'","SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName LIKE LOWER('%Nguyễn Văn A%');"],
   ["Những cải tiến được thực hiện bởi nhân viên 'Nguyễn Văn A' thuộc nhóm 'Team Beta' có ngày ra mắt trong khoảng từ tháng 1 đến tháng 3 năm 2024 là gì?","SELECT Jidouka.ImprovementName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId JOIN GroupDC ON Jidouka.GroupDCId = GroupDC.GroupDCId WHERE Author.AuthorName LIKE LOWER('%Nguyễn Văn A%') AND GroupDC.GroupDCName LIKE LOWER('%Team Beta%') AND Jidouka.DateCreate BETWEEN '2024-01-01' AND '2024-03-31';"],
]

In [ ]:
data = [
    ["Which innovations have been applied to 'Car Manufacturing' products?", "SELECT ImprovementName FROM Jidouka WHERE ProductApply LIKE LOWER('%Car Manufacturing%');"],
    ["Which innovations are linked to both 'Tool A' and 'Tool B'?","SELECT DISTINCT Jidouka.ImprovementName FROM Jidouka WHERE Jidouka.JidoukaId IN (SELECT JidoukaTool.JidoukaId FROM JidoukaTool WHERE ToolId = (SELECT Tool.ToolId FROM Tool WHERE Tool.ToolName LIKE LOWER('%Tool A%'))) AND Jidouka.JidoukaId IN (SELECT JidoukaTool.JidoukaId FROM JidoukaTool WHERE ToolId = (SELECT Tool.ToolId FROM Tool WHERE Tool.ToolName LIKE LOWER('%Tool B%')));"],
    ["Which tools were used in innovations authored by 'Alice Smith'?","SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.AuthorId = (SELECT Author.AuthorId FROM Author WHERE Author.AuthorName LIKE LOWER('%Alice Smith%'));"],
    ["List all jobs that have no associated innovations.","SELECT Job.JobName FROM Job LEFT JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.JobId IS NULL;"],
    ["What are the innovations created in 2023?","SELECT ImprovementName FROM Jidouka WHERE YEAR(DateCreate) = 2023;"],
    ["List all tools with their descriptions.","SELECT ToolName, ToolDescription FROM Tool;"],
    ["List all tools with 'automation' in their description.","SELECT ToolName FROM Tool WHERE LOWER(ToolDescription) LIKE '%automation%';"],
    ["Which tools are used by innovations created in 2022?","SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON Jidouka.JidoukaId = JidoukaTool.JidoukaId WHERE YEAR(Jidouka.DateCreate) = 2022;"],
    ["Which innovations saved more than 100 hours in 2023?","SELECT ImprovementName, TotalTimeSaved FROM Jidouka WHERE TotalTimeSaved > 100 AND YEAR(DateCreate) = 2023;"],
    ["Which innovations were launched in 2023?", "SELECT ImprovementName FROM Jidouka WHERE YEAR(DateCreate) = 2023;"],
    ["List the innovations that saved more than 100 hours in total and were created in 2023.","SELECT ImprovementName FROM Jidouka WHERE TotalTimeSaved > 100 AND YEAR(DateCreate) = 2023;"],


    ["Danh sách các cải tiến liên quan đến sản phẩm 'Robot AI'","SELECT Jidouka.ImprovementName FROM Jidouka WHERE Jidouka.ProductApply LIKE LOWER('%Robot AI%');"],
    ["Danh sách các cải tiến được thực hiện trong tháng đầu tiên của mỗi quý năm 2023","SELECT Jidouka.ImprovementName FROM Jidouka WHERE YEAR(Jidouka.DateCreate) = 2023 AND MONTH(Jidouka.DateCreate) IN (1, 4, 7, 10);"],
    ["Danh sách các nhóm trong bộ phận DC6 đã sử dụng công cụ hỗ trợ tự động hóa?","SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE Department.DepartmentName LIKE LOWER('%DC6%') AND Tool.ToolDescription LIKE LOWER('%hỗ trợ tự động hóa%');"],
    ["Danh sách các nhóm trong bộ phận DC4 đã thực hiện cải tiến với công cụ CAD?","SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE Department.DepartmentName LIKE LOWER('%DC4%') AND Tool.ToolName LIKE LOWER('%CAD%');"],
    ["Các nhóm thuộc bộ phận DC5 có công cụ hỗ trợ nào?", "SELECT DISTINCT GroupDC.GroupDCName, Tool.ToolName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%DC5%');"],
    ["Các nhóm nào trong bộ phận DC5 đã áp dụng công cụ hỗ trợ tự động hóa?","SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE Department.DepartmentName LIKE LOWER('%DC5%') AND Tool.ToolDescription LIKE LOWER('%hỗ trợ tự động hóa%');"],
    ["Tác giả nào đã thực hiện cải tiến đầu tiên trong năm 2023?","SELECT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE Jidouka.DateCreate >LIKE LOWER('%2023-01-01%') ORDER BY Jidouka.DateCreate ASC LIMIT 1;"],
    ["Tác giả nào đã thực hiện cải tiến đầu tiên trong năm 2023?", "SELECT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE Jidouka.DateCreate >LIKE LOWER('%2023-01-01%') ORDER BY Jidouka.DateCreate ASC LIMIT 1;"],
    ["Danh sách các nhóm trong bộ phận DC3 đã áp dụng cải tiến tự động hóa?","SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%DC3%') AND Jidouka.ImprovementName LIKE LOWER('%jidouka%');"],
    ["Danh sách các nhóm trong DC4 đã thực hiện cải tiến với công cụ CAD?","SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE Department.DepartmentName LIKE LOWER('%DC4%') AND Tool.ToolName LIKE LOWER('%CAD%');"],
    ["Các cải tiến được tạo trong tháng 12 năm 2023 là gì?","SELECT Jidouka.ImprovementName FROM Jidouka WHERE MONTH(Jidouka.DateCreate) = 12 AND YEAR(Jidouka.DateCreate) = 2023;"],
    ["Danh sách các cải tiến tạo sau tháng 6 năm 2023 và tiết kiệm được trên 50 giờ", "SELECT Jidouka.ImprovementName FROM Jidouka WHERE Jidouka.DateCreate > '2023-06-30' AND Jidouka.TotalTimeSaved > 50;"],
    ["Các cải tiến được tạo trong tháng 12 năm 2023 là gì?", "SELECT Jidouka.ImprovementName FROM Jidouka WHERE MONTH(Jidouka.DateCreate) = 12 AND YEAR(Jidouka.DateCreate) = 2023;"],
    ["Cải tiến nào được tạo vào tháng 2 của năm nay và sử dụng ít nhất một công cụ?", "SELECT DISTINCT Jidouka.ImprovementName FROM Jidouka JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId WHERE MONTH(Jidouka.DateCreate) = 2 AND YEAR(Jidouka.DateCreate) = YEAR(CURDATE());"],

]

In [ ]:
data = [
    ["Which innovations have been applied to 'Car Manufacturing' products?", "SELECT ImprovementName FROM Jidouka WHERE ProductApply LIKE LOWER('%Car Manufacturing%');"],
    ["Which innovations have been applied to Car Manufacturing products?", "SELECT ImprovementName FROM Jidouka WHERE ProductApply LIKE LOWER('%Car Manufacturing%');"],
    ["Which innovations have been applied to 'Bicycle Manufacturing' products?", "SELECT ImprovementName FROM Jidouka WHERE ProductApply LIKE LOWER('%Bicycle Manufacturing%');"],
    ["Which innovations have been applied to excel products?", "SELECT ImprovementName FROM Jidouka WHERE ProductApply LIKE LOWER('%excel%');"],
    ["Which innovations are linked to both 'Tool A' and 'Tool B'?","SELECT DISTINCT Jidouka.ImprovementName FROM Jidouka WHERE Jidouka.JidoukaId IN (SELECT JidoukaTool.JidoukaId FROM JidoukaTool WHERE ToolId = (SELECT Tool.ToolId FROM Tool WHERE Tool.ToolName LIKE LOWER('%Tool A%'))) AND Jidouka.JidoukaId IN (SELECT JidoukaTool.JidoukaId FROM JidoukaTool WHERE ToolId = (SELECT Tool.ToolId FROM Tool WHERE Tool.ToolName LIKE LOWER('%Tool B%')));"],
    ["Which innovations are linked to both Tool C and Tool D?","SELECT DISTINCT Jidouka.ImprovementName FROM Jidouka WHERE Jidouka.JidoukaId IN (SELECT JidoukaTool.JidoukaId FROM JidoukaTool WHERE ToolId = (SELECT Tool.ToolId FROM Tool WHERE Tool.ToolName LIKE LOWER('%Tool C%'))) AND Jidouka.JidoukaId IN (SELECT JidoukaTool.JidoukaId FROM JidoukaTool WHERE ToolId = (SELECT Tool.ToolId FROM Tool WHERE Tool.ToolName LIKE LOWER('%Tool D%')));"],
    ["Which innovations are linked to both Tool C and Tool D?","SELECT DISTINCT Jidouka.ImprovementName FROM Jidouka WHERE Jidouka.JidoukaId IN (SELECT JidoukaTool.JidoukaId FROM JidoukaTool WHERE ToolId = (SELECT Tool.ToolId FROM Tool WHERE Tool.ToolName LIKE LOWER('%Tool C%'))) AND Jidouka.JidoukaId IN (SELECT JidoukaTool.JidoukaId FROM JidoukaTool WHERE ToolId = (SELECT Tool.ToolId FROM Tool WHERE Tool.ToolName LIKE LOWER('%Tool D%')));"],
    ["Which tools were used in innovations authored by 'Alice Smith'?","SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.AuthorId = (SELECT Author.AuthorId FROM Author WHERE Author.AuthorName LIKE LOWER('%Alice Smith%'));"],
    ["Which tools were used in innovations authored by Nguyen Van A?","SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.AuthorId = (SELECT Author.AuthorId FROM Author WHERE Author.AuthorName LIKE LOWER('%Nguyen Van A%'));"],
    ["Which tools were used in innovations authored by Pham Van Dong?","SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.AuthorId = (SELECT Author.AuthorId FROM Author WHERE Author.AuthorName LIKE LOWER('%Pham Van Dong%'));"],
    ["Which tools were used in innovations authored by Chu Dinh Vuong?","SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.AuthorId = (SELECT Author.AuthorId FROM Author WHERE Author.AuthorName LIKE LOWER('%Chu Dinh Vuong%'));"],
    ["Which tools were used in innovations authored by Chu Dinh Vuong?","SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.AuthorId = (SELECT Author.AuthorId FROM Author WHERE Author.AuthorName LIKE LOWER('%Chu Dinh Vuong%'));"],
    ["Which tools were used in innovations authored by Chu Dinh Vuong?","SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.AuthorId = (SELECT Author.AuthorId FROM Author WHERE Author.AuthorName LIKE LOWER('%Chu Dinh Vuong%'));"],
    ["List all jobs that have no associated innovations.","SELECT Job.JobName FROM Job LEFT JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.JobId IS NULL;"],
    ["List all jobs that have no associated innovations.","SELECT Job.JobName FROM Job LEFT JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.JobId IS NULL;"],
    ["List all jobs that have no associated innovations.","SELECT Job.JobName FROM Job LEFT JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.JobId IS NULL;"],
    ["List all jobs that have no associated innovations.","SELECT Job.JobName FROM Job LEFT JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.JobId IS NULL;"],
    ["What are the innovations created in 2023?","SELECT ImprovementName FROM Jidouka WHERE YEAR(DateCreate) = 2023;"],
    ["What are the innovations created in 2024?","SELECT ImprovementName FROM Jidouka WHERE YEAR(DateCreate) = 2024;"],
    ["What are the innovations created in 2023?","SELECT ImprovementName FROM Jidouka WHERE YEAR(DateCreate) = 2020;"],
    ["What are the innovations created in 2023?","SELECT ImprovementName FROM Jidouka WHERE YEAR(DateCreate) = 2021;"],
    ["What are the innovations created in 2023?","SELECT ImprovementName FROM Jidouka WHERE YEAR(DateCreate) = 2019;"],
    ["List all tools with their descriptions.","SELECT ToolName, ToolDescription FROM Tool;"],
    ["List all tools with their descriptions.","SELECT ToolName, ToolDescription FROM Tool;"],    
    ["List all tools with their descriptions.","SELECT ToolName, ToolDescription FROM Tool;"], 
    ["List all tools with their descriptions.","SELECT ToolName, ToolDescription FROM Tool;"],     
    ["List all tools with 'automation' in their description.","SELECT ToolName FROM Tool WHERE LOWER(ToolDescription) LIKE '%automation%';"],
    ["List all tools with 'excel' in their description.","SELECT ToolName FROM Tool WHERE LOWER(ToolDescription) LIKE '%excel%';"],
    ["List all tools with 'word' in their description.","SELECT ToolName FROM Tool WHERE LOWER(ToolDescription) LIKE '%word%';"],
    ["List all tools with 'contributed to' in their description.","SELECT ToolName FROM Tool WHERE LOWER(ToolDescription) LIKE '%contributed to%';"],       
    ["Which tools are used by innovations created in 2022?","SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON Jidouka.JidoukaId = JidoukaTool.JidoukaId WHERE YEAR(Jidouka.DateCreate) = 2022;"],
    ["Which tools are used by innovations created in 2024?","SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON Jidouka.JidoukaId = JidoukaTool.JidoukaId WHERE YEAR(Jidouka.DateCreate) = 2024;"],
    ["Which tools are used by innovations created in 2020?","SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON Jidouka.JidoukaId = JidoukaTool.JidoukaId WHERE YEAR(Jidouka.DateCreate) = 2020;"],
    ["Which tools are used by innovations created in 2021?","SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON Jidouka.JidoukaId = JidoukaTool.JidoukaId WHERE YEAR(Jidouka.DateCreate) = 2021;"],
    ["Which innovations saved less than 100 hours in 2023?","SELECT ImprovementName, TotalTimeSaved FROM Jidouka WHERE TotalTimeSaved < 100 AND YEAR(DateCreate) = 2023;"],
    ["Which innovations saved more than 100 hours in 2023?","SELECT ImprovementName, TotalTimeSaved FROM Jidouka WHERE TotalTimeSaved > 100 AND YEAR(DateCreate) = 2023;"],
    ["Which innovations saved more than 100 hours in 2024?","SELECT ImprovementName, TotalTimeSaved FROM Jidouka WHERE TotalTimeSaved > 100 AND YEAR(DateCreate) = 2024;"],
    ["Which innovations saved more than 200 hours in 2024?","SELECT ImprovementName, TotalTimeSaved FROM Jidouka WHERE TotalTimeSaved > 200 AND YEAR(DateCreate) = 2024;"],
    ["Which innovations saved more than 100 hours in 2020?","SELECT ImprovementName, TotalTimeSaved FROM Jidouka WHERE TotalTimeSaved > 100 AND YEAR(DateCreate) = 2020;"],    
    ["Which innovations were launched in 2023?", "SELECT ImprovementName FROM Jidouka WHERE YEAR(DateCreate) = 2023;"],
    ["Which innovations were launched in 2021?", "SELECT ImprovementName FROM Jidouka WHERE YEAR(DateCreate) = 2021;"],
    ["Which innovations were launched in 2020?", "SELECT ImprovementName FROM Jidouka WHERE YEAR(DateCreate) = 2020;"],
    ["Which innovations were launched in 2019?", "SELECT ImprovementName FROM Jidouka WHERE YEAR(DateCreate) = 2019;"],
    ["Which innovations were launched in 2018?", "SELECT ImprovementName FROM Jidouka WHERE YEAR(DateCreate) = 2018;"],
    ["List the innovations that saved more than 100 hours in total and were created in 2023.","SELECT ImprovementName FROM Jidouka WHERE TotalTimeSaved > 100 AND YEAR(DateCreate) = 2023;"],
    ["List the innovations that saved more than 200 hours in total and were created in 2020.","SELECT ImprovementName FROM Jidouka WHERE TotalTimeSaved > 200 AND YEAR(DateCreate) = 2020;"],
    ["List the innovations that saved more than 200 hours in total and were created in 2021.","SELECT ImprovementName FROM Jidouka WHERE TotalTimeSaved > 200 AND YEAR(DateCreate) = 2021;"],
    ["List the innovations that saved at least 200 hours in total and were created in 2020.","SELECT ImprovementName FROM Jidouka WHERE TotalTimeSaved >= 200 AND YEAR(DateCreate) = 2020;"],
    ["List the innovations that saved at least 200 hours in total and were created in 2024.","SELECT ImprovementName FROM Jidouka WHERE TotalTimeSaved >= 200 AND YEAR(DateCreate) = 2024;"],


    ["Danh sách các cải tiến liên quan đến sản phẩm 'Robot AI'","SELECT Jidouka.ImprovementName FROM Jidouka WHERE Jidouka.ProductApply LIKE LOWER('%Robot AI%');"],
    ["Danh sách các cải tiến liên quan đến sản phẩm 'Web DB'","SELECT Jidouka.ImprovementName FROM Jidouka WHERE Jidouka.ProductApply LIKE LOWER('%WEB DB%');"],
    ["Danh sách các cải tiến liên quan đến sản phẩm 'database'","SELECT Jidouka.ImprovementName FROM Jidouka WHERE Jidouka.ProductApply LIKE LOWER('%database%');"],    
    ["Danh sách các cải tiến được thực hiện trong tháng đầu tiên của mỗi quý năm 2023","SELECT Jidouka.ImprovementName FROM Jidouka WHERE YEAR(Jidouka.DateCreate) = 2023 AND MONTH(Jidouka.DateCreate) IN (1, 4, 7, 10);"],
    ["Danh sách các cải tiến được thực hiện trong tháng đầu tiên của mỗi quý năm 2021","SELECT Jidouka.ImprovementName FROM Jidouka WHERE YEAR(Jidouka.DateCreate) = 2021 AND MONTH(Jidouka.DateCreate) IN (1, 4, 7, 10);"],
    ["Danh sách các cải tiến được thực hiện trong tháng đầu tiên của mỗi quý năm 2022","SELECT Jidouka.ImprovementName FROM Jidouka WHERE YEAR(Jidouka.DateCreate) = 2022 AND MONTH(Jidouka.DateCreate) IN (1, 4, 7, 10);"],  
    ["Danh sách các cải tiến được thực hiện trong tháng đầu tiên của mỗi quý năm 2020","SELECT Jidouka.ImprovementName FROM Jidouka WHERE YEAR(Jidouka.DateCreate) = 2022 AND MONTH(Jidouka.DateCreate) IN (1, 4, 7, 10);"], 
    ["Danh sách các nhóm trong bộ phận DC6 đã sử dụng công cụ hỗ trợ tự động hóa?","SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE Department.DepartmentName LIKE LOWER('%DC6%')"],
    ["Danh sách các nhóm trong bộ phận DC7 đã sử dụng công cụ hỗ trợ tự động hóa?","SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE Department.DepartmentName LIKE LOWER('%DC7%')"],
    ["Danh sách các nhóm trong bộ phận DC7 đã sử dụng công cụ hỗ trợ tự động hóa?","SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE Department.DepartmentName LIKE LOWER('%DC8%')"],
    ["Danh sách các nhóm trong bộ phận DC8 đã thực hiện cải tiến với công cụ CAD?","SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE Department.DepartmentName LIKE LOWER('%DC8%') AND Tool.ToolName LIKE LOWER('%CAD%');"],
    ["Danh sách các nhóm trong bộ phận DC8 đã thực hiện cải tiến với công cụ CAD?","SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE Department.DepartmentName LIKE LOWER('%DC4%') AND Tool.ToolName LIKE LOWER('%CAD%');"],    
    ["Các nhóm thuộc bộ phận DC5 có công cụ hỗ trợ nào?", "SELECT DISTINCT GroupDC.GroupDCName, Tool.ToolName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%DC5%');"],
    ["Các nhóm thuộc bộ phận DC4 có công cụ hỗ trợ nào?", "SELECT DISTINCT GroupDC.GroupDCName, Tool.ToolName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%DC%');"],
    ["Các nhóm nào trong bộ phận DC5 đã áp dụng công cụ hỗ trợ tự động hóa?","SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE Department.DepartmentName LIKE LOWER('%DC5%') AND Tool.ToolDescription LIKE LOWER('%hỗ trợ tự động hóa%');"],
    ["Tác giả nào đã thực hiện cải tiến đầu tiên trong năm 2023?","SELECT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE YEAR(Jidouka.DateCreate) LIKE LOWER('%2023%') ORDER BY Jidouka.DateCreate ASC LIMIT 1;"],
    ["Tác giả nào đã thực hiện cải tiến đầu tiên trong năm 2024?", "SELECT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE YEAR(Jidouka.DateCreate) LIKE LOWER('%2024%') ORDER BY Jidouka.DateCreate ASC LIMIT 1;"],
    ["Tác giả nào đã thực hiện cải tiến đầu tiên trong năm 2020?", "SELECT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE YEAR(Jidouka.DateCreate) LIKE LOWER('%2020%') ORDER BY Jidouka.DateCreate ASC LIMIT 1;"],    
    ["Danh sách các nhóm trong bộ phận DC3 đã áp dụng cải tiến tự động hóa?","SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%DC3%') AND Jidouka.ImprovementName LIKE LOWER('%jidouka%');"],
    ["Danh sách các nhóm trong bộ phận DC5 đã áp dụng cải tiến tự động hóa?","SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE LOWER('%DC5%') AND Jidouka.ImprovementName LIKE LOWER('%jidouka%');"],
    ["Danh sách các nhóm trong DC4 đã thực hiện cải tiến với công cụ CAD?","SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE Department.DepartmentName LIKE LOWER('%DC4%') AND Tool.ToolName LIKE LOWER('%CAD%');"],
    ["Danh sách các nhóm trong DC4 đã thực hiện cải tiến với công cụ CAD?","SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE Department.DepartmentName LIKE LOWER('%DC4%') AND Tool.ToolName LIKE LOWER('%CAD%');"],
    ["Danh sách các nhóm trong DC4 đã thực hiện cải tiến với công cụ CAD?","SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE Department.DepartmentName LIKE LOWER('%DC4%') AND Tool.ToolName LIKE LOWER('%CAD%');"],
    ["Danh sách các nhóm trong DC4 đã thực hiện cải tiến với công cụ CAD?","SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE Department.DepartmentName LIKE LOWER('%DC4%') AND Tool.ToolName LIKE LOWER('%CAD%');"],    
    ["Các cải tiến được tạo trong tháng 12 năm 2023 là gì?","SELECT Jidouka.ImprovementName FROM Jidouka WHERE MONTH(Jidouka.DateCreate) = 12 AND YEAR(Jidouka.DateCreate) = 2023;"],
    ["Các cải tiến được tạo trong tháng 12 năm 2024 là gì?","SELECT Jidouka.ImprovementName FROM Jidouka WHERE MONTH(Jidouka.DateCreate) = 12 AND YEAR(Jidouka.DateCreate) = 2024;"],
    ["Danh sách các cải tiến tạo sau tháng 6 năm 2023 và tiết kiệm được trên 50 giờ", "SELECT Jidouka.ImprovementName FROM Jidouka WHERE Jidouka.DateCreate > '2023-06-30' AND Jidouka.TotalTimeSaved > 50;"],
    ["Các cải tiến được tạo trong tháng 12 năm 2023 là gì?", "SELECT Jidouka.ImprovementName FROM Jidouka WHERE MONTH(Jidouka.DateCreate) = 12 AND YEAR(Jidouka.DateCreate) = 2023;"],
    ["Cải tiến nào được tạo vào tháng 2 của năm nay và sử dụng ít nhất một công cụ?", "SELECT DISTINCT Jidouka.ImprovementName FROM Jidouka JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId WHERE MONTH(Jidouka.DateCreate) = 2 AND YEAR(Jidouka.DateCreate) = YEAR(CURDATE());"],
    ["Danh sách các cải tiến tạo sau tháng 6 năm 2023 và tiết kiệm được trên 50 giờ", "SELECT Jidouka.ImprovementName FROM Jidouka WHERE Jidouka.DateCreate > '2023-06-30' AND Jidouka.TotalTimeSaved > 50;"],
    ["Các cải tiến được tạo trong tháng 12 năm 2023 là gì?", "SELECT Jidouka.ImprovementName FROM Jidouka WHERE MONTH(Jidouka.DateCreate) = 12 AND YEAR(Jidouka.DateCreate) = 2023;"],
    ["Cải tiến nào được tạo vào tháng 2 của năm nay và sử dụng ít nhất một công cụ?", "SELECT DISTINCT Jidouka.ImprovementName FROM Jidouka JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId WHERE MONTH(Jidouka.DateCreate) = 2 AND YEAR(Jidouka.DateCreate) = YEAR(CURDATE());"],
    ["Danh sách các cải tiến tạo sau tháng 6 năm 2023 và tiết kiệm được trên 50 giờ", "SELECT Jidouka.ImprovementName FROM Jidouka WHERE Jidouka.DateCreate > '2023-06-30' AND Jidouka.TotalTimeSaved > 50;"],
    ["Các cải tiến được tạo trong tháng 12 năm 2023 là gì?", "SELECT Jidouka.ImprovementName FROM Jidouka WHERE MONTH(Jidouka.DateCreate) = 12 AND YEAR(Jidouka.DateCreate) = 2023;"],
    ["Cải tiến nào được tạo vào tháng 2 của năm nay và sử dụng ít nhất một công cụ?", "SELECT DISTINCT Jidouka.ImprovementName FROM Jidouka JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId WHERE MONTH(Jidouka.DateCreate) = 2 AND YEAR(Jidouka.DateCreate) = YEAR(CURDATE());"],


]

In [19]:
len(data)

25

In [9]:
import re
def modify_query(query):
    modified_query = re.sub(r"= '([^']*)'", r"LIKE LOWER('%\1%')", query)
    return modified_query

In [10]:
data2 = []
for i in range(len(data)):
    lst = []
    lst.append(data[i][0])
    lst.append(modify_query(data[i][1]))
    lst.append(data[i][0])
    lst.append(data[i][0])
    lst.append(modify_query(data[i][1]))
    data2.append(lst)

In [11]:
dct = {'previous_question':[], 'previous_answer':[], 'schema_linking':[], 'question':[], 'answer':[]}
for i in range(len(data2)):
    dct['previous_question'].append(data[i][0])
    dct['previous_answer'].append(data2[i][1])
    dct['schema_linking'].append(data2[i][2])
    dct['question'].append(data2[i][3])
    dct['answer'].append(data2[i][4])

In [12]:
import pandas as pd 
df3 = pd.DataFrame(dct)
df3 = df3.sample(frac=1)

In [13]:
len(df3)

210

In [15]:
df3.to_csv('output210_fixed_errors.csv', index=False)