In [ ]:
data = [
    ["What is the content of innovation with ID 456?",
     "SELECT ImprovementContent FROM Jidouka WHERE JidoukaId = 456;",
     "{Tables: [Jidouka], Columns: [Jidouka.ImprovementContent, Jidouka.JidoukaId], Foreign keys: [], Possible cell values: [456]}",
     "Who created this innovation?",
     "SELECT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE Jidouka.JidoukaId = 456;"],

    # 2
    ["Which tools were used for the innovation with ID 789?",
     "SELECT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId WHERE JidoukaTool.JidoukaId = 789;",
     "{Tables: [Tool, JidoukaTool], Columns: [Tool.ToolName, JidoukaTool.JidoukaId, JidoukaTool.ToolId], Foreign keys: [JidoukaTool.ToolId=Tool.ToolId], Possible cell values: [789]}",
     "What is the description of these tools?",
     "SELECT Tool.ToolName, Tool.ToolDescription FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId WHERE JidoukaTool.JidoukaId = 789;"],

    # 3
    ["What innovations were launched in 2023?",
     "SELECT ImprovementContent, DateCreate FROM Jidouka WHERE YEAR(DateCreate) = 2023;",
     "{Tables: [Jidouka], Columns: [Jidouka.ImprovementContent, Jidouka.DateCreate], Foreign keys: [], Possible cell values: [2023]}",
     "Who created these innovations?",
     "SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE YEAR(Jidouka.DateCreate) = 2023;"],

    # 4
    ["List all authors associated with the department 'Research'.",
     "SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE LOWER(Department.DepartmentName) = 'research';",
     "{Tables: [Author, Jidouka, Department], Columns: [Author.AuthorName, Jidouka.AuthorId, Jidouka.DepartmentId, Department.DepartmentId, Department.DepartmentName], Foreign keys: [Jidouka.AuthorId=Author.AuthorId, Jidouka.DepartmentId=Department.DepartmentId], Possible cell values: [Research]}",
     "Which innovations did these authors create?",
     "SELECT Jidouka.ImprovementContent, Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE LOWER(Department.DepartmentName) = 'research';"],

    # 5
    ["How many countries are there in the world?",
     "There are 195 countries in the world.",
     None,
     "Which is the largest country by area?",
     "Russia is the largest country by area."],

    # 6
    ["What are the tools linked to innovations involving the task type 'Analysis'?",
     "SELECT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE LOWER(Jidouka.JobName) LIKE '%analysis%';",
     "{Tables: [Tool, JidoukaTool, Jidouka], Columns: [Tool.ToolName, JidoukaTool.ToolId, JidoukaTool.JidoukaId, Jidouka.JobName, Jidouka.JidoukaId], Foreign keys: [JidoukaTool.ToolId=Tool.ToolId, JidoukaTool.JidoukaId=Jidouka.JidoukaId], Possible cell values: [Analysis]}",
     "What are the details of these tools?",
     "SELECT Tool.ToolName, Tool.ToolDescription FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE LOWER(Jidouka.JobName) LIKE '%analysis%';"],

    # 7
    ["What is the capital of France?",
     "The capital of France is Paris.",
     None,
     "How about Japan?",
     "The capital of Japan is Tokyo."],

    # 8
    ["Which innovations saved more than 100 hours?",
     "SELECT ImprovementContent, TotalTimeSaved FROM Jidouka WHERE TotalTimeSaved > 100;",
     "{Tables: [Jidouka], Columns: [Jidouka.ImprovementContent, Jidouka.TotalTimeSaved], Foreign keys: [], Possible cell values: [>100]}",
     "What jobs were associated with these innovations?",
     "SELECT Job.JobName, Jidouka.ImprovementContent FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.TotalTimeSaved > 100;"],

    # 9
    ["Who are the employees linked to team 'Development A'?",
     "SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId JOIN GroupDC ON Jidouka.GroupDCId = GroupDC.GroupDCId WHERE LOWER(GroupDC.GroupDCName) = 'development a';",
     "{Tables: [Author, Jidouka, GroupDC], Columns: [Author.AuthorName, Jidouka.AuthorId, Jidouka.GroupDCId, GroupDC.GroupDCId, GroupDC.GroupDCName], Foreign keys: [Jidouka.AuthorId=Author.AuthorId, Jidouka.GroupDCId=GroupDC.GroupDCId], Possible cell values: [Development A]}",
     "What are the innovations created by this team?",
     "SELECT Jidouka.ImprovementContent FROM Jidouka JOIN GroupDC ON Jidouka.GroupDCId = GroupDC.GroupDCId WHERE LOWER(GroupDC.GroupDCName) = 'development a';"],

    # 10
    ["What is the approximate number of stars in the Milky Way?",
     "I am not sure about the exact number of stars in the Milky Way.",
     None,
     "How many planets are in the Solar System?",
     "There are 8 planets in the Solar System."],

    # 11
    ["Which departments were linked to innovations launched in 2022?",
     "SELECT DISTINCT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE YEAR(Jidouka.DateCreate) = 2022;",
     "{Tables: [Department, Jidouka], Columns: [Department.DepartmentName, Jidouka.DepartmentId, Jidouka.DateCreate], Foreign keys: [Jidouka.DepartmentId=Department.DepartmentId], Possible cell values: [2022]}",
     "Which authors contributed to these innovations?",
     "SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE YEAR(Jidouka.DateCreate) = 2022;"],

    # 12
    ["What is the tool description for 'Tool A'?",
     "SELECT ToolDescription FROM Tool WHERE LOWER(ToolName) = 'tool a';",
     "{Tables: [Tool], Columns: [Tool.ToolDescription, Tool.ToolName], Foreign keys: [], Possible cell values: [Tool A]}",
     "Which innovations used this tool?",
     "SELECT Jidouka.ImprovementContent FROM Jidouka JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE LOWER(Tool.ToolName) = 'tool a';"] ,  

    ["Which job types are associated with innovations?",
     "SELECT DISTINCT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId;",
     "{Tables: [Job, Jidouka], Columns: [Job.JobName, Job.JobId, Jidouka.JobId], Foreign keys: [Jidouka.JobId=Job.JobId], Possible cell values: []}",
     "Which innovations are associated with the job type 'Testing'?",
     "SELECT Jidouka.ImprovementContent FROM Jidouka JOIN Job ON Jidouka.JobId = Job.JobId WHERE LOWER(Job.JobName) = 'testing';"],

    # 2
    ["How many hours were saved by all innovations?",
     "SELECT SUM(TotalTimeSaved) AS TotalHoursSaved FROM Jidouka;",
     "{Tables: [Jidouka], Columns: [Jidouka.TotalTimeSaved], Foreign keys: [], Possible cell values: []}",
     "What is the average time saved per innovation?",
     "SELECT AVG(TotalTimeSaved) AS AverageHoursSaved FROM Jidouka;"],

    # 3
    ["List the design centers involved in improvements.",
     "SELECT DISTINCT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId;",
     "{Tables: [Department, Jidouka], Columns: [Department.DepartmentName, Department.DepartmentId, Jidouka.DepartmentId], Foreign keys: [Jidouka.DepartmentId=Department.DepartmentId], Possible cell values: []}",
     "Which design center contributed to the most improvements?",
     "SELECT Department.DepartmentName, COUNT(*) AS ImprovementCount FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId GROUP BY Department.DepartmentName ORDER BY ImprovementCount DESC LIMIT 1;"],

    # 4
    ["What are the main features of tool 'Automation Kit'?",
     "SELECT ToolDescription FROM Tool WHERE LOWER(ToolName) = 'automation kit';",
     "{Tables: [Tool], Columns: [Tool.ToolDescription, Tool.ToolName], Foreign keys: [], Possible cell values: [Automation Kit]}",
     "Which improvements used this tool?",
     "SELECT Jidouka.ImprovementContent FROM Jidouka JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE LOWER(Tool.ToolName) = 'automation kit';"],

    # 5
    ["What is the total number of innovations?",
     "SELECT COUNT(*) AS TotalInnovations FROM Jidouka;",
     "{Tables: [Jidouka], Columns: [Jidouka.JidoukaId], Foreign keys: [], Possible cell values: []}",
     "How many were created by the 'Development' department?",
     "SELECT COUNT(*) AS TotalInnovations FROM Jidouka JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE LOWER(Department.DepartmentName) = 'development';"],

    # 6
    ["What is the capital of Germany?",
     "The capital of Germany is Berlin.",
     None,
     "What is the capital of Canada?",
     "The capital of Canada is Ottawa."],

    # 7
    ["Which innovations were implemented in 'Team Alpha'?",
     "SELECT Jidouka.ImprovementContent FROM Jidouka JOIN GroupDC ON Jidouka.GroupDCId = GroupDC.GroupDCId WHERE LOWER(GroupDC.GroupDCName) = 'team alpha';",
     "{Tables: [Jidouka, GroupDC], Columns: [Jidouka.ImprovementContent, Jidouka.GroupDCId, GroupDC.GroupDCName], Foreign keys: [Jidouka.GroupDCId=GroupDC.GroupDCId], Possible cell values: [Team Alpha]}",
     "Who created these innovations?",
     "SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId JOIN GroupDC ON Jidouka.GroupDCId = GroupDC.GroupDCId WHERE LOWER(GroupDC.GroupDCName) = 'team alpha';"],

    # 8
    ["How many tools are available in the database?",
     "SELECT COUNT(*) AS TotalTools FROM Tool;",
     "{Tables: [Tool], Columns: [Tool.ToolId], Foreign keys: [], Possible cell values: []}",
     "What are the names of these tools?",
     "SELECT ToolName FROM Tool;"],

    # 9
    ["Which improvements have no tools linked to them?",
     "SELECT Jidouka.ImprovementContent FROM Jidouka WHERE Jidouka.JidoukaId NOT IN (SELECT DISTINCT JidoukaId FROM JidoukaTool);",
     "{Tables: [Jidouka, JidoukaTool], Columns: [Jidouka.ImprovementContent, Jidouka.JidoukaId, JidoukaTool.JidoukaId], Foreign keys: [], Possible cell values: []}",
     "What is the total time saved by these improvements?",
     "SELECT SUM(TotalTimeSaved) AS TotalTimeSaved FROM Jidouka WHERE Jidouka.JidoukaId NOT IN (SELECT DISTINCT JidoukaId FROM JidoukaTool);"],

    # 10
    ["What is the meaning of life?",
     "I am not sure about the exact meaning of life.",
     None,
     "What is the speed of light?",
     "The speed of light is approximately 299,792 kilometers per second."],

    # 11
    ["Which innovations used more than three tools?",
     "SELECT Jidouka.ImprovementContent FROM Jidouka JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId GROUP BY Jidouka.JidoukaId HAVING COUNT(JidoukaTool.ToolId) > 3;",
     "{Tables: [Jidouka, JidoukaTool], Columns: [Jidouka.ImprovementContent, Jidouka.JidoukaId, JidoukaTool.ToolId], Foreign keys: [Jidouka.JidoukaId=JidoukaTool.JidoukaId], Possible cell values: []}",
     "What tools were linked to these innovations?",
     "SELECT Jidouka.ImprovementContent, Tool.ToolName FROM Jidouka JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId GROUP BY Jidouka.JidoukaId HAVING COUNT(JidoukaTool.ToolId) > 3;"],

    # 12
    ["What are the most recent innovations?",
     "SELECT ImprovementContent, DateCreate FROM Jidouka ORDER BY DateCreate DESC LIMIT 5;",
     "{Tables: [Jidouka], Columns: [Jidouka.ImprovementContent, Jidouka.DateCreate], Foreign keys: [], Possible cell values: []}",
     "Who created these innovations?",
     "SELECT ImprovementContent, Author.AuthorName FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId ORDER BY Jidouka.DateCreate DESC LIMIT 5;"],

    # 13
    ["Which team saved the most hours?",
     "SELECT GroupDC.GroupDCName, SUM(Jidouka.TotalTimeSaved) AS TotalTimeSaved FROM Jidouka JOIN GroupDC ON Jidouka.GroupDCId = GroupDC.GroupDCId GROUP BY GroupDC.GroupDCName ORDER BY TotalTimeSaved DESC LIMIT 1;",
     "{Tables: [Jidouka, GroupDC], Columns: [Jidouka.TotalTimeSaved, Jidouka.GroupDCId, GroupDC.GroupDCName], Foreign keys: [Jidouka.GroupDCId=GroupDC.GroupDCId], Possible cell values: []}",
     "What are the innovations linked to this team?",
     "SELECT Jidouka.ImprovementContent FROM Jidouka JOIN GroupDC ON Jidouka.GroupDCId = GroupDC.GroupDCId GROUP BY GroupDC.GroupDCName ORDER BY SUM(Jidouka.TotalTimeSaved) DESC LIMIT 1;"],

    # 14
    ["What is the size of the Earth?",
     "The Earth's equatorial diameter is approximately 12,742 kilometers.",
     None,
     "What is the mass of the Earth?",
     "The Earth's mass is approximately 5.97 × 10^24 kilograms."],

    # 15
    ["Which innovations involve both 'Task A' and 'Tool B'?",
     "SELECT Jidouka.ImprovementContent FROM Jidouka JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE LOWER(Jidouka.JobName) = 'task a' AND LOWER(Tool.ToolName) = 'tool b';",
     "{Tables: [Jidouka, JidoukaTool, Tool], Columns: [Jidouka.ImprovementContent, Jidouka.JobName, Jidouka.JidoukaId, JidoukaTool.ToolId, JidoukaTool.JidoukaId, Tool.ToolName], Foreign keys: [JidoukaTool.ToolId=Tool.ToolId, Jidouka.JidoukaId=JidoukaTool.JidoukaId], Possible cell values: ['tool A','tool B']}",
     "How much time did these innovations save?",
     "SELECT SUM(Jidouka.TotalTimeSaved) AS TotalTimeSaved FROM Jidouka JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE LOWER(Jidouka.JobName) = 'task a' AND LOWER(Tool.ToolName) = 'tool b';"],
    ["Which author worked on the improvement with ID 101?", 
     "SELECT AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE Jidouka.JidoukaId = 101;", 
     "{Tables: [Author, Jidouka], Columns: [Author.AuthorName, Jidouka.JidoukaId], Foreign keys: [Jidouka.AuthorId=Author.AuthorId], Possible cell values: [101]}",
     "What department is this author associated with?", 
     "SELECT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE Jidouka.JidoukaId = 101;"],

    ["What tools were used in improvement ID 202?", 
     "SELECT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId WHERE JidoukaTool.JidoukaId = 202;", 
     "{Tables: [Tool, JidoukaTool], Columns: [Tool.ToolName, JidoukaTool.JidoukaId], Foreign keys: [JidoukaTool.JidoukaId=Jidouka.JidoukaId], Possible cell values: [202]}",
     "Which jobs used these tools?", 
     "SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.JidoukaId = 202;"],

    ["Who created the innovation with ID 303?", 
     "SELECT AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE Jidouka.JidoukaId = 303;", 
     "{Tables: [Author, Jidouka], Columns: [Author.AuthorName, Jidouka.JidoukaId], Foreign keys: [Jidouka.AuthorId=Author.AuthorId], Possible cell values: [303]}",
     "What is the improvement content for this innovation?", 
     "SELECT ImprovementContent FROM Jidouka WHERE JidoukaId = 303;"],

    ["What are the job names associated with improvement ID 404?", 
     "SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.JidoukaId = 404;", 
     "{Tables: [Job, Jidouka], Columns: [Job.JobName, Jidouka.JidoukaId], Foreign keys: [Jidouka.JobId=Job.JobId], Possible cell values: [404]}",
     "What is the description of this improvement?", 
     "SELECT Description FROM Jidouka WHERE JidoukaId = 404;"],

    ["How many jobs applied the improvement with ID 505?", 
     "SELECT TotalJobApplied FROM Jidouka WHERE JidoukaId = 505;", 
     "{Tables: [Jidouka], Columns: [Jidouka.TotalJobApplied, Jidouka.JidoukaId], Foreign keys: [], Possible cell values: [505]}",
     "What tools were used in this improvement?", 
     "SELECT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId WHERE JidoukaTool.JidoukaId = 505;"],

    ["Which employees are associated with the job 'Task B'?", 
     "SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE Jidouka.JobName = 'Task B';", 
     "{Tables: [Author, Jidouka], Columns: [Author.AuthorName, Jidouka.JobName], Foreign keys: [Jidouka.AuthorId=Author.AuthorId], Possible cell values: ['Task B']}",
     "Which department is responsible for this job?", 
     "SELECT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE Jidouka.JobName = 'Task B';"],

    ["Which job applied the most number of improvements?", 
     "SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId ORDER BY Jidouka.TotalJobApplied DESC LIMIT 1;", 
     "{Tables: [Job, Jidouka], Columns: [Job.JobName, Jidouka.TotalJobApplied], Foreign keys: [Jidouka.JobId=Job.JobId], Possible cell values: []}",
     "What is the improvement content for this job?", 
     "SELECT ImprovementContent FROM Jidouka WHERE JobId = (SELECT JobId FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId ORDER BY Jidouka.TotalJobApplied DESC LIMIT 1);"],

    ["Which tool was used in the most innovations?", 
     "SELECT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId GROUP BY Tool.ToolId ORDER BY COUNT(JidoukaTool.JidoukaId) DESC LIMIT 1;", 
     "{Tables: [Tool, JidoukaTool], Columns: [Tool.ToolName, JidoukaTool.JidoukaId], Foreign keys: [JidoukaTool.ToolId=Tool.ToolId], Possible cell values: []}",
     "How many innovations used this tool?", 
     "SELECT COUNT(JidoukaTool.JidoukaId) FROM JidoukaTool WHERE ToolId = (SELECT ToolId FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId GROUP BY Tool.ToolId ORDER BY COUNT(JidoukaTool.JidoukaId) DESC LIMIT 1);"],

    ["Which group is responsible for innovation ID 606?", 
     "SELECT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId WHERE Jidouka.JidoukaId = 606;", 
     "{Tables: [GroupDC, Jidouka], Columns: [GroupDC.GroupDCName, Jidouka.JidoukaId], Foreign keys: [Jidouka.GroupDCId=GroupDC.GroupDCId], Possible cell values: [606]}",
     "What department is this group part of?", 
     "SELECT Department.DepartmentName FROM Department JOIN GroupDC ON Department.DepartmentId = GroupDC.DepartmentId WHERE GroupDC.GroupDCId = 606;"],

    ["How much time was saved by the innovation with ID 707?", 
     "SELECT TotalTimeSaved FROM Jidouka WHERE JidoukaId = 707;", 
     "{Tables: [Jidouka], Columns: [Jidouka.TotalTimeSaved, Jidouka.JidoukaId], Foreign keys: [], Possible cell values: [707]}",
     "Which jobs were associated with this innovation?", 
     "SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.JidoukaId = 707;"],

    ["Which improvements were made by the 'Design Center A'?", 
     "SELECT Jidouka.ImprovementContent FROM Jidouka JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName = 'Design Center A';", 
     "{Tables: [Jidouka, Department], Columns: [Jidouka.ImprovementContent, Department.DepartmentName], Foreign keys: [Jidouka.DepartmentId=Department.DepartmentId], Possible cell values: ['Design Center A']}",
     "What jobs are linked to these innovations?", 
     "SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.DepartmentId = (SELECT DepartmentId FROM Department WHERE DepartmentName = 'Design Center A');"],

    ["What is the creation date for innovation ID 808?", 
     "SELECT DateCreate FROM Jidouka WHERE JidoukaId = 808;", 
     "{Tables: [Jidouka], Columns: [Jidouka.DateCreate, Jidouka.JidoukaId], Foreign keys: [], Possible cell values: [808]}",
     "What is the job associated with this innovation?", 
     "SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.JidoukaId = 808;"],

    ["What is the job ID for innovation ID 909?", 
     "SELECT JobId FROM Jidouka WHERE JidoukaId = 909;", 
     "{Tables: [Jidouka], Columns: [Jidouka.JobId, Jidouka.JidoukaId], Foreign keys: [], Possible cell values: [909]}",
     "Which authors worked on this job?", 
     "SELECT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE Jidouka.JobId = (SELECT JobId FROM Jidouka WHERE JidoukaId = 909);"],

    ["What is the total time saved by innovation with ID 1010?", 
     "SELECT TotalTimeSaved FROM Jidouka WHERE JidoukaId = 1010;", 
     "{Tables: [Jidouka], Columns: [Jidouka.TotalTimeSaved, Jidouka.JidoukaId], Foreign keys: [], Possible cell values: [1010]}",
     "What tools were involved in this innovation?", 
     "SELECT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId WHERE JidoukaTool.JidoukaId = 1010;"],

    ["Who created the innovation for 'Task C'?", 
     "SELECT AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE Jidouka.JobName = 'Task C';", 
     "{Tables: [Author, Jidouka], Columns: [Author.AuthorName, Jidouka.JobName], Foreign keys: [Jidouka.AuthorId=Author.AuthorId], Possible cell values: ['Task C']}",
     "What is the improvement content of this innovation?", 
     "SELECT ImprovementContent FROM Jidouka WHERE JobName = 'Task C';"],

    ["What department worked on innovation ID 1111?", 
     "SELECT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE Jidouka.JidoukaId = 1111;", 
     "{Tables: [Department, Jidouka], Columns: [Department.DepartmentName, Jidouka.JidoukaId], Foreign keys: [Jidouka.DepartmentId=Department.DepartmentId], Possible cell values: [1111]}",
     "What is the job associated with this department?", 
     "SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.DepartmentId = (SELECT DepartmentId FROM Department WHERE DepartmentName = 'Design Center B');"],

    ["What is the description of innovation ID 1212?", 
     "SELECT Description FROM Jidouka WHERE JidoukaId = 1212;", 
     "{Tables: [Jidouka], Columns: [Jidouka.Description, Jidouka.JidoukaId], Foreign keys: [], Possible cell values: [1212]}",
     "What tool was used in this innovation?", 
     "SELECT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId WHERE JidoukaTool.JidoukaId = 1212;"],

    ["Which jobs were associated with innovation ID 1313?", 
     "SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.JidoukaId = 1313;", 
     "{Tables: [Job, Jidouka], Columns: [Job.JobName, Jidouka.JidoukaId], Foreign keys: [Jidouka.JobId=Job.JobId], Possible cell values: [1313]}",
     "What department is responsible for these jobs?", 
     "SELECT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE Jidouka.JidoukaId = 1313;"],

    ["Who worked on the innovation with ID 1414?", 
     "SELECT AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE Jidouka.JidoukaId = 1414;", 
     "{Tables: [Author, Jidouka], Columns: [Author.AuthorName, Jidouka.JidoukaId], Foreign keys: [Jidouka.AuthorId=Author.AuthorId], Possible cell values: [1414]}",
     "What is the improvement content for this innovation?", 
     "SELECT ImprovementContent FROM Jidouka WHERE JidoukaId = 1414;"],

    ["What tools were used for innovation ID 1515?", 
     "SELECT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId WHERE JidoukaTool.JidoukaId = 1515;", 
     "{Tables: [Tool, JidoukaTool], Columns: [Tool.ToolName, JidoukaTool.JidoukaId], Foreign keys: [JidoukaTool.JidoukaId=Jidouka.JidoukaId], Possible cell values: [1515]}",
     "What is the total time saved by this innovation?", 
     "SELECT TotalTimeSaved FROM Jidouka WHERE JidoukaId = 1515;"],

    ["What jobs applied the improvement with ID 1616?", 
     "SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.JidoukaId = 1616;", 
     "{Tables: [Job, Jidouka], Columns: [Job.JobName, Jidouka.JidoukaId], Foreign keys: [Jidouka.JobId=Job.JobId], Possible cell values: [1616]}",
     "Which department is responsible for this job?", 
     "SELECT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE Jidouka.JidoukaId = 1616;"],

    ["Which innovation was created by 'Team X'?", 
     "SELECT Jidouka.ImprovementContent FROM Jidouka JOIN GroupDC ON Jidouka.GroupDCId = GroupDC.GroupDCId WHERE GroupDC.GroupDCName = 'Team X';", 
     "{Tables: [Jidouka, GroupDC], Columns: [Jidouka.ImprovementContent, GroupDC.GroupDCName], Foreign keys: [Jidouka.GroupDCId=GroupDC.GroupDCId], Possible cell values: ['Team X']}",
     "What jobs were associated with this innovation?", 
     "SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.GroupDCId = (SELECT GroupDCId FROM GroupDC WHERE GroupDCName = 'Team X');"],

    ["Which department worked on innovation ID 1717?", 
     "SELECT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE Jidouka.JidoukaId = 1717;", 
     "{Tables: [Department, Jidouka], Columns: [Department.DepartmentName, Jidouka.JidoukaId], Foreign keys: [Jidouka.DepartmentId=Department.DepartmentId], Possible cell values: [1717]}",
     "What is the job associated with this department?", 
     "SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.DepartmentId = (SELECT DepartmentId FROM Department WHERE DepartmentName = 'Design Center C');"],

    ["Which author created innovation ID 1818?", 
     "SELECT AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE Jidouka.JidoukaId = 1818;", 
     "{Tables: [Author, Jidouka], Columns: [Author.AuthorName, Jidouka.JidoukaId], Foreign keys: [Jidouka.AuthorId=Author.AuthorId], Possible cell values: [1818]}",
     "What tools were used in this innovation?", 
     "SELECT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId WHERE JidoukaTool.JidoukaId = 1818;"],

    ["Which jobs applied the improvement with ID 1919?", 
     "SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.JidoukaId = 1919;", 
     "{Tables: [Job, Jidouka], Columns: [Job.JobName, Jidouka.JidoukaId], Foreign keys: [Jidouka.JobId=Job.JobId], Possible cell values: [1919]}",
     "Which department is responsible for this improvement?", 
     "SELECT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE Jidouka.JidoukaId = 1919;"],

    ["What is the creation date of innovation ID 2020?", 
     "SELECT DateCreate FROM Jidouka WHERE JidoukaId = 2020;", 
     "{Tables: [Jidouka], Columns: [Jidouka.DateCreate, Jidouka.JidoukaId], Foreign keys: [], Possible cell values: [2020]}",
     "What is the improvement content of this innovation?", 
     "SELECT ImprovementContent FROM Jidouka WHERE JidoukaId = 2020;"],

    ["Which jobs applied the most improvements?", 
     "SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId ORDER BY Jidouka.TotalJobApplied DESC LIMIT 1;", 
     "{Tables: [Job, Jidouka], Columns: [Job.JobName, Jidouka.TotalJobApplied], Foreign keys: [Jidouka.JobId=Job.JobId], Possible cell values: []}",
     "What is the improvement content for this job?", 
     "SELECT ImprovementContent FROM Jidouka WHERE JobId = (SELECT JobId FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId ORDER BY Jidouka.TotalJobApplied DESC LIMIT 1);"],

    ["Which tool is used in the most innovations?", 
     "SELECT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId GROUP BY Tool.ToolId ORDER BY COUNT(JidoukaTool.JidoukaId) DESC LIMIT 1;", 
     "{Tables: [Tool, JidoukaTool], Columns: [Tool.ToolName, JidoukaTool.JidoukaId], Foreign keys: [JidoukaTool.ToolId=Tool.ToolId], Possible cell values: []}",
     "How many innovations used this tool?", 
     "SELECT COUNT(JidoukaTool.JidoukaId) FROM JidoukaTool WHERE ToolId = (SELECT ToolId FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId GROUP BY Tool.ToolId ORDER BY COUNT(JidoukaTool.JidoukaId) DESC LIMIT 1);"],

    ["What department is responsible for the innovation with ID 2121?", 
     "SELECT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE Jidouka.JidoukaId = 2121;", 
     "{Tables: [Department, Jidouka], Columns: [Department.DepartmentName, Jidouka.JidoukaId], Foreign keys: [Jidouka.DepartmentId=Department.DepartmentId], Possible cell values: [2121]}",
     "What is the job associated with this department?", 
     "SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.DepartmentId = (SELECT DepartmentId FROM Department WHERE DepartmentName = 'Design Center D');"],

    ["What is the release date of innovation ID 2222?", 
     "SELECT ReleaseDate FROM Jidouka WHERE JidoukaId = 2222;", 
     "{Tables: [Jidouka], Columns: [Jidouka.ReleaseDate, Jidouka.JidoukaId], Foreign keys: [], Possible cell values: [2222]}",
     "What tools were used in this innovation?", 
     "SELECT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId WHERE JidoukaTool.JidoukaId = 2222;"],

    ["What is the description of the innovation with ID 2323?", 
     "SELECT Description FROM Jidouka WHERE JidoukaId = 2323;", 
     "{Tables: [Jidouka], Columns: [Jidouka.Description, Jidouka.JidoukaId], Foreign keys: [], Possible cell values: [2323]}",
     "What is the improvement content for this innovation?", 
     "SELECT ImprovementContent FROM Jidouka WHERE JidoukaId = 2323;"],

    ["Which jobs applied improvement with ID 2424?", 
     "SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.JidoukaId = 2424;", 
     "{Tables: [Job, Jidouka], Columns: [Job.JobName, Jidouka.JidoukaId], Foreign keys: [Jidouka.JobId=Job.JobId], Possible cell values: [2424]}",
     "Which department is responsible for this job?", 
     "SELECT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE Jidouka.JidoukaId = 2424;"],

    ["Who is the author of innovation with ID 2525?", 
     "SELECT AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE Jidouka.JidoukaId = 2525;", 
     "{Tables: [Author, Jidouka], Columns: [Author.AuthorName, Jidouka.JidoukaId], Foreign keys: [Jidouka.AuthorId=Author.AuthorId], Possible cell values: [2525]}",
     "What tools were used in this innovation?", 
     "SELECT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId WHERE JidoukaTool.JidoukaId = 2525;"],

    ["What is the total number of jobs applied to improvement with ID 2626?", 
     "SELECT TotalJobApplied FROM Jidouka WHERE JidoukaId = 2626;", 
     "{Tables: [Jidouka], Columns: [Jidouka.TotalJobApplied, Jidouka.JidoukaId], Foreign keys: [], Possible cell values: [2626]}",
     "What is the job associated with this innovation?", 
     "SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.JidoukaId = 2626;"],

    ["What department worked on innovation ID 2727?", 
     "SELECT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE Jidouka.JidoukaId = 2727;", 
     "{Tables: [Department, Jidouka], Columns: [Department.DepartmentName, Jidouka.JidoukaId], Foreign keys: [Jidouka.DepartmentId=Department.DepartmentId], Possible cell values: [2727]}",
     "What is the total time saved by this innovation?", 
     "SELECT TotalTimeSaved FROM Jidouka WHERE JidoukaId = 2727;"],

    ["Which tool was used for innovation with ID 2828?", 
     "SELECT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId WHERE JidoukaTool.JidoukaId = 2828;", 
     "{Tables: [Tool, JidoukaTool], Columns: [Tool.ToolName, JidoukaTool.JidoukaId], Foreign keys: [JidoukaTool.ToolId=Tool.ToolId], Possible cell values: [2828]}",
     "What is the release date for this innovation?", 
     "SELECT ReleaseDate FROM Jidouka WHERE JidoukaId = 2828;"],

    ["What jobs applied the most number of innovations?", 
     "SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId ORDER BY Jidouka.TotalJobApplied DESC LIMIT 1;", 
     "{Tables: [Job, Jidouka], Columns: [Job.JobName, Jidouka.TotalJobApplied], Foreign keys: [Jidouka.JobId=Job.JobId], Possible cell values: []}",
     "What is the improvement content for this job?", 
     "SELECT ImprovementContent FROM Jidouka WHERE JobId = (SELECT JobId FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId ORDER BY Jidouka.TotalJobApplied DESC LIMIT 1);"],

    ["Which department is responsible for innovation with ID 2929?", 
     "SELECT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE Jidouka.JidoukaId = 2929;", 
     "{Tables: [Department, Jidouka], Columns: [Department.DepartmentName, Jidouka.JidoukaId], Foreign keys: [Jidouka.DepartmentId=Department.DepartmentId], Possible cell values: [2929]}",
     "What is the improvement content of this innovation?", 
     "SELECT ImprovementContent FROM Jidouka WHERE JidoukaId = 2929;"],

    ["Who created innovation ID 3030?", 
     "SELECT AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE Jidouka.JidoukaId = 3030;", 
     "{Tables: [Author, Jidouka], Columns: [Author.AuthorName, Jidouka.JidoukaId], Foreign keys: [Jidouka.AuthorId=Author.AuthorId], Possible cell values: [3030]}",
     "What tool was used in this innovation?", 
     "SELECT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId WHERE JidoukaTool.JidoukaId = 3030;"],

    ["Which jobs applied improvement ID 3131?", 
     "SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.JidoukaId = 3131;", 
     "{Tables: [Job, Jidouka], Columns: [Job.JobName, Jidouka.JidoukaId], Foreign keys: [Jidouka.JobId=Job.JobId], Possible cell values: [3131]}",
     "Which department is responsible for this job?", 
     "SELECT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE Jidouka.JidoukaId = 3131;"],

    ["What is the total number of hours saved by innovation ID 3232?", 
     "SELECT TotalTimeSaved FROM Jidouka WHERE JidoukaId = 3232;", 
     "{Tables: [Jidouka], Columns: [Jidouka.TotalTimeSaved, Jidouka.JidoukaId], Foreign keys: [], Possible cell values: [3232]}",
     "What is the job associated with this innovation?", 
     "SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.JidoukaId = 3232;"],

    ["What department worked on innovation ID 3333?", 
     "SELECT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE Jidouka.JidoukaId = 3333;", 
     "{Tables: [Department, Jidouka], Columns: [Department.DepartmentName, Jidouka.JidoukaId], Foreign keys: [Jidouka.DepartmentId=Department.DepartmentId], Possible cell values: [3333]}",
     "Which tool was used for this innovation?", 
     "SELECT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId WHERE JidoukaTool.JidoukaId = 3333;"],

    ["Who worked on the innovation with ID 3434?", 
     "SELECT AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE Jidouka.JidoukaId = 3434;", 
     "{Tables: [Author, Jidouka], Columns: [Author.AuthorName, Jidouka.JidoukaId], Foreign keys: [Jidouka.AuthorId=Author.AuthorId], Possible cell values: [3434]}",
     "What job was applied in this innovation?", 
     "SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.JidoukaId = 3434;"],

    ["What is the launch date of innovation ID 3535?", 
     "SELECT ReleaseDate FROM Jidouka WHERE JidoukaId = 3535;", 
     "{Tables: [Jidouka], Columns: [Jidouka.ReleaseDate, Jidouka.JidoukaId], Foreign keys: [], Possible cell values: [3535]}",
     "What is the improvement content of this innovation?", 
     "SELECT ImprovementContent FROM Jidouka WHERE JidoukaId = 3535;"],

    ["What is the total number of jobs applied for innovation ID 3636?", 
     "SELECT TotalJobApplied FROM Jidouka WHERE JidoukaId = 3636;", 
     "{Tables: [Jidouka], Columns: [Jidouka.TotalJobApplied, Jidouka.JidoukaId], Foreign keys: [], Possible cell values: [3636]}",
     "What department applied this innovation?", 
     "SELECT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE Jidouka.JidoukaId = 3636;"],

    ["Who authored innovation ID 3737?", 
     "SELECT AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE Jidouka.JidoukaId = 3737;", 
     "{Tables: [Author, Jidouka], Columns: [Author.AuthorName, Jidouka.JidoukaId], Foreign keys: [Jidouka.AuthorId=Author.AuthorId], Possible cell values: [3737]}",
     "What tool was used in this innovation?", 
     "SELECT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId WHERE JidoukaTool.JidoukaId = 3737;"],

    ["What department worked on improvement ID 3838?", 
     "SELECT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE Jidouka.JidoukaId = 3838;", 
     "{Tables: [Department, Jidouka], Columns: [Department.DepartmentName, Jidouka.JidoukaId], Foreign keys: [Jidouka.DepartmentId=Department.DepartmentId], Possible cell values: [3838]}",
     "What is the release date for this innovation?", 
     "SELECT ReleaseDate FROM Jidouka WHERE JidoukaId = 3838;"],

    ["What are the details of the innovation with ID 456?",
     "SELECT ImprovementContent, Description, Video, DetailDocument FROM Jidouka WHERE JidoukaId = 456;",
     "{Tables: [Jidouka], Columns: [Jidouka.ImprovementContent, Jidouka.Description, Jidouka.Video, Jidouka.DetailDocument, Jidouka.JidoukaId], Foreign keys: [], Possible cell values: [456]}",
     "Which tools are linked to this innovation?",
     "SELECT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId WHERE JidoukaTool.JidoukaId = 456;"],

    ["List all the innovations created by the 'Design Center A'.",
     "SELECT Jidouka.ImprovementContent FROM Jidouka JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName = 'Design Center A';",
     "{Tables: [Jidouka, Department], Columns: [Jidouka.ImprovementContent, Jidouka.DepartmentId, Department.DepartmentId, Department.DepartmentName], Foreign keys: [Jidouka.DepartmentId=Department.DepartmentId], Possible cell values: ['Design Center A']}",
     "Which teams contributed to these innovations?",
     "SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName = 'Design Center A';"],

    ["What is the job type for the innovation '456'?",
     "SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.JidoukaId = 456;",
     "{Tables: [Job, Jidouka], Columns: [Job.JobName, Jidouka.JobId, Jidouka.JidoukaId], Foreign keys: [Jidouka.JobId=Job.JobId], Possible cell values: [456]}",
     "Who is the author of this innovation?",
     "SELECT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE Jidouka.JidoukaId = 456;"],

    ["Which innovations were created in '2022'?",
     "SELECT ImprovementContent FROM Jidouka WHERE YEAR(DateCreate) = 2022;",
     "{Tables: [Jidouka], Columns: [Jidouka.ImprovementContent, Jidouka.DateCreate], Foreign keys: [], Possible cell values: [2022]}",
     "How many hours were saved by these innovations?",
     "SELECT SUM(TotalTimeSaved) FROM Jidouka WHERE YEAR(DateCreate) = 2022;"],

    ["Which tools have descriptions containing 'automation'?",
     "SELECT ToolName FROM Tool WHERE ToolDescription LIKE '%automation%';",
     "{Tables: [Tool], Columns: [Tool.ToolName, Tool.ToolDescription], Foreign keys: [], Possible cell values: ['automation']}",
     "Which innovations use these tools?",
     "SELECT DISTINCT Jidouka.ImprovementContent FROM Jidouka JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE Tool.ToolDescription LIKE '%automation%';"],

    # Not related to schema
    ["What is the speed of light?",
     "The speed of light is approximately 299,792 kilometers per second.",
     None,
     "What is the chemical formula for water?",
     "The chemical formula for water is H2O."],

    ["How far is the Moon from Earth?",
     "The average distance from the Moon to Earth is about 384,400 kilometers.",
     None,
     "What is the largest planet in our solar system?",
     "The largest planet in our solar system is Jupiter."],

    ["What is the capital of Japan?",
     "The capital of Japan is Tokyo.",
     None,
     "What is the population of Tokyo?",
     "I am not sure about the exact population of Tokyo."],

    ["Who painted the Mona Lisa?",
     "The Mona Lisa was painted by Leonardo da Vinci.",
     None,
     "When was it painted?",
     "It was painted between 1503 and 1506, although Leonardo may have worked on it for several years beyond that."],

    ["What is the height of Mount Everest?",
     "Mount Everest's height is approximately 8,848 meters.",
     None,
     "What is the second tallest mountain in the world?",
     "The second tallest mountain in the world is K2, which is approximately 8,611 meters tall."],

    ["Which jobs are linked to innovations created by 'Author X'?",
     "SELECT DISTINCT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName = 'Author X';",
     "{Tables: [Job, Jidouka, Author], Columns: [Job.JobName, Jidouka.JobId, Jidouka.AuthorId, Author.AuthorId, Author.AuthorName], Foreign keys: [Jidouka.JobId=Job.JobId, Jidouka.AuthorId=Author.AuthorId], Possible cell values: ['Author X']}",
     "Which departments are associated with these jobs?",
     "SELECT DISTINCT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId JOIN Job ON Jidouka.JobId = Job.JobId JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName = 'Author X';"],

    ["List all groups in 'Design Center B'.",
     "SELECT GroupDCName FROM GroupDC JOIN Department ON GroupDC.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName = 'Design Center B';",
     "{Tables: [GroupDC, Department], Columns: [GroupDC.GroupDCName, GroupDC.DepartmentId, Department.DepartmentId, Department.DepartmentName], Foreign keys: [GroupDC.DepartmentId=Department.DepartmentId], Possible cell values: ['Design Center B']}",
     "What innovations are linked to these groups?",
     "SELECT Jidouka.ImprovementContent FROM Jidouka JOIN GroupDC ON Jidouka.GroupDCId = GroupDC.GroupDCId JOIN Department ON GroupDC.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName = 'Design Center B';"],

    ["Which tools have been used in innovations with 'saved hours' greater than 500?",
     "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.TotalTimeSaved > 500;",
     "{Tables: [Tool, JidoukaTool, Jidouka], Columns: [Tool.ToolName, Tool.ToolId, JidoukaTool.ToolId, JidoukaTool.JidoukaId, Jidouka.TotalTimeSaved], Foreign keys: [JidoukaTool.ToolId=Tool.ToolId, JidoukaTool.JidoukaId=Jidouka.JidoukaId], Possible cell values: [500]}",
     "Which departments created these innovations?",
     "SELECT DISTINCT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE Jidouka.TotalTimeSaved > 500;"],

    ["Which innovations were launched before 2020?",
     "SELECT ImprovementContent FROM Jidouka WHERE YEAR(DateCreate) < 2020;",
     "{Tables: [Jidouka], Columns: [Jidouka.ImprovementContent, Jidouka.DateCreate], Foreign keys: [], Possible cell values: [2020]}",
     "What is the total number of jobs applied for these innovations?",
     "SELECT SUM(TotalJobApplied) FROM Jidouka WHERE YEAR(DateCreate) < 2020;"],

    ["Who are the authors of innovations in 'Team Alpha'?",
     "SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId JOIN GroupDC ON Jidouka.GroupDCId = GroupDC.GroupDCId WHERE GroupDC.GroupDCName = 'Team Alpha';",
     "{Tables: [Author, Jidouka, GroupDC], Columns: [Author.AuthorName, Author.AuthorId, Jidouka.AuthorId, Jidouka.GroupDCId, GroupDC.GroupDCId, GroupDC.GroupDCName], Foreign keys: [Jidouka.AuthorId=Author.AuthorId, Jidouka.GroupDCId=GroupDC.GroupDCId], Possible cell values: ['Team Alpha']}",
     "Which tools were used in these innovations?",
     "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId JOIN GroupDC ON Jidouka.GroupDCId = GroupDC.GroupDCId WHERE GroupDC.GroupDCName = 'Team Alpha';"],

    # Not related to schema
    ["What is the boiling point of water?",
     "The boiling point of water is 100°C (212°F) at sea level.",
     None,
     "What is the freezing point of water?",
     "The freezing point of water is 0°C (32°F)."],

    ["Who wrote 'Hamlet'?",
     "William Shakespeare wrote 'Hamlet'.",
     None,
     "What is another famous play by Shakespeare?",
     "'Romeo and Juliet' is another famous play by Shakespeare."],

    ["What is the chemical symbol for gold?",
     "The chemical symbol for gold is Au.",
     None,
     "What is its atomic number?",
     "The atomic number of gold is 79."],

    ["How many continents are there on Earth?",
     "There are seven continents on Earth.",
     None,
     "Which is the largest continent?",
     "Asia is the largest continent."],

    ["Who is the author of 'Pride and Prejudice'?",
     "'Pride and Prejudice' was written by Jane Austen.",
     None,
     "When was it published?",
     "It was first published in 1813."],

    ["What is the job name associated with improvement ID 3939?", 
     "SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.JidoukaId = 3939;", 
     "{Tables: [Job, Jidouka], Columns: [Job.JobName, Jidouka.JidoukaId], Foreign keys: [Jidouka.JobId=Job.JobId], Possible cell values: [3939]}",
     "What tool was used in this job?", 
     "SELECT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId WHERE JidoukaTool.JidoukaId = 3939;"],

    ["What is the total time saved by improvement with ID 4040?", 
     "SELECT TotalTimeSaved FROM Jidouka WHERE JidoukaId = 4040;", 
     "{Tables: [Jidouka], Columns: [Jidouka.TotalTimeSaved, Jidouka.JidoukaId], Foreign keys: [], Possible cell values: [4040]}",
     "Which department applied this innovation?", 
     "SELECT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE Jidouka.JidoukaId = 4040;"],

    ["Who is the author of innovation with ID 4141?", 
     "SELECT AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE Jidouka.JidoukaId = 4141;", 
     "{Tables: [Author, Jidouka], Columns: [Author.AuthorName, Jidouka.JidoukaId], Foreign keys: [Jidouka.AuthorId=Author.AuthorId], Possible cell values: [4141]}",
     "What is the description of this innovation?", 
     "SELECT Description FROM Jidouka WHERE JidoukaId = 4141;"],

    ["What is the total number of jobs that applied improvement ID 4242?", 
     "SELECT TotalJobApplied FROM Jidouka WHERE JidoukaId = 4242;", 
     "{Tables: [Jidouka], Columns: [Jidouka.TotalJobApplied, Jidouka.JidoukaId], Foreign keys: [], Possible cell values: [4242]}",
     "What is the improvement content for this job?", 
     "SELECT ImprovementContent FROM Jidouka WHERE JidoukaId = 4242;"],

    ["Which department is associated with innovation ID 4343?", 
     "SELECT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE Jidouka.JidoukaId = 4343;", 
     "{Tables: [Department, Jidouka], Columns: [Department.DepartmentName, Jidouka.JidoukaId], Foreign keys: [Jidouka.DepartmentId=Department.DepartmentId], Possible cell values: [4343]}",
     "What job is associated with this innovation?", 
     "SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.JidoukaId = 4343;"],

    ["What tool was used for innovation with ID 4444?", 
     "SELECT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId WHERE JidoukaTool.JidoukaId = 4444;", 
     "{Tables: [Tool, JidoukaTool], Columns: [Tool.ToolName, JidoukaTool.JidoukaId], Foreign keys: [JidoukaTool.ToolId=Tool.ToolId], Possible cell values: [4444]}",
     "What is the creation date of this innovation?", 
     "SELECT DateCreate FROM Jidouka WHERE JidoukaId = 4444;"],

    ["Which department worked on improvement ID 4545?", 
     "SELECT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE Jidouka.JidoukaId = 4545;", 
     "{Tables: [Department, Jidouka], Columns: [Department.DepartmentName, Jidouka.JidoukaId], Foreign keys: [Jidouka.DepartmentId=Department.DepartmentId], Possible cell values: [4545]}",
     "What is the total time saved by this innovation?", 
     "SELECT TotalTimeSaved FROM Jidouka WHERE JidoukaId = 4545;"],

    ["What is the product name for innovation ID 4646?", 
     "SELECT ProductName FROM Jidouka WHERE JidoukaId = 4646;", 
     "{Tables: [Jidouka], Columns: [Jidouka.ProductName, Jidouka.JidoukaId], Foreign keys: [], Possible cell values: [4646]}",
     "What is the improvement content of this innovation?", 
     "SELECT ImprovementContent FROM Jidouka WHERE JidoukaId = 4646;"],

    ["Who is the author of improvement ID 4747?", 
     "SELECT AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE Jidouka.JidoukaId = 4747;", 
     "{Tables: [Author, Jidouka], Columns: [Author.AuthorName, Jidouka.JidoukaId], Foreign keys: [Jidouka.AuthorId=Author.AuthorId], Possible cell values: [4747]}",
     "What job is associated with this innovation?", 
     "SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.JidoukaId = 4747;"],

    ["Which department worked on improvement with ID 4848?", 
     "SELECT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE Jidouka.JidoukaId = 4848;", 
     "{Tables: [Department, Jidouka], Columns: [Department.DepartmentName, Jidouka.JidoukaId], Foreign keys: [Jidouka.DepartmentId=Department.DepartmentId], Possible cell values: [4848]}",
     "What is the total number of jobs applied for this innovation?", 
     "SELECT TotalJobApplied FROM Jidouka WHERE JidoukaId = 4848;"],

    ["What tool was used in innovation ID 4949?", 
     "SELECT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId WHERE JidoukaTool.JidoukaId = 4949;", 
     "{Tables: [Tool, JidoukaTool], Columns: [Tool.ToolName, JidoukaTool.JidoukaId], Foreign keys: [JidoukaTool.ToolId=Tool.ToolId], Possible cell values: [4949]}",
     "What is the creation date of this innovation?", 
     "SELECT DateCreate FROM Jidouka WHERE JidoukaId = 4949;"],

    ["What is the total time saved for innovation ID 5050?", 
     "SELECT TotalTimeSaved FROM Jidouka WHERE JidoukaId = 5050;", 
     "{Tables: [Jidouka], Columns: [Jidouka.TotalTimeSaved, Jidouka.JidoukaId], Foreign keys: [], Possible cell values: [5050]}",
     "What is the department associated with this innovation?", 
     "SELECT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE Jidouka.JidoukaId = 5050;"],

    ["Which jobs applied improvement ID 5151?", 
     "SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.JidoukaId = 5151;", 
     "{Tables: [Job, Jidouka], Columns: [Job.JobName, Jidouka.JidoukaId], Foreign keys: [Jidouka.JobId=Job.JobId], Possible cell values: [5151]}",
     "What is the improvement content for this job?", 
     "SELECT ImprovementContent FROM Jidouka WHERE JidoukaId = 5151;"],

    ["What is the description for innovation ID 5252?", 
     "SELECT Description FROM Jidouka WHERE JidoukaId = 5252;", 
     "{Tables: [Jidouka], Columns: [Jidouka.Description, Jidouka.JidoukaId], Foreign keys: [], Possible cell values: [5252]}",
     "What department worked on this innovation?", 
     "SELECT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE Jidouka.JidoukaId = 5252;"],

    ["Who authored improvement ID 5353?", 
     "SELECT AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE Jidouka.JidoukaId = 5353;", 
     "{Tables: [Author, Jidouka], Columns: [Author.AuthorName, Jidouka.JidoukaId], Foreign keys: [Jidouka.AuthorId=Author.AuthorId], Possible cell values: [5353]}",
     "What is the product name for this innovation?", 
     "SELECT ProductName FROM Jidouka WHERE JidoukaId = 5353;"],

    ["What is the total number of jobs applied for innovation ID 5454?", 
     "SELECT TotalJobApplied FROM Jidouka WHERE JidoukaId = 5454;", 
     "{Tables: [Jidouka], Columns: [Jidouka.TotalJobApplied, Jidouka.JidoukaId], Foreign keys: [], Possible cell values: [5454]}",
     "Which department applied this innovation?", 
     "SELECT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE Jidouka.JidoukaId = 5454;"],

    ["Which innovations use the tool 'Tool A'?",
     "SELECT Jidouka.ImprovementContent FROM Jidouka JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE Tool.ToolName = 'Tool A';",
     "{Tables: [Jidouka, JidoukaTool, Tool], Columns: [Jidouka.ImprovementContent, Jidouka.JidoukaId, JidoukaTool.JidoukaId, JidoukaTool.ToolId, Tool.ToolName], Foreign keys: [JidoukaTool.JidoukaId=Jidouka.JidoukaId, JidoukaTool.ToolId=Tool.ToolId], Possible cell values: ['Tool A']}",
     "What is the total saved time by these innovations?",
     "SELECT SUM(Jidouka.TotalTimeSaved) FROM Jidouka JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE Tool.ToolName = 'Tool A';"],

    ["List all innovations linked to jobs under 'Team Beta'.",
     "SELECT Jidouka.ImprovementContent FROM Jidouka JOIN GroupDC ON Jidouka.GroupDCId = GroupDC.GroupDCId WHERE GroupDC.GroupDCName = 'Team Beta';",
     "{Tables: [Jidouka, GroupDC], Columns: [Jidouka.ImprovementContent, Jidouka.GroupDCId, GroupDC.GroupDCId, GroupDC.GroupDCName], Foreign keys: [Jidouka.GroupDCId=GroupDC.GroupDCId], Possible cell values: ['Team Beta']}",
     "Who authored these innovations?",
     "SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId JOIN GroupDC ON Jidouka.GroupDCId = GroupDC.GroupDCId WHERE GroupDC.GroupDCName = 'Team Beta';"],

    ["Which innovations were created using tools with descriptions containing 'machine learning'?",
     "SELECT Jidouka.ImprovementContent FROM Jidouka JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE Tool.ToolDescription LIKE '%machine learning%';",
     "{Tables: [Jidouka, JidoukaTool, Tool], Columns: [Jidouka.ImprovementContent, Jidouka.JidoukaId, JidoukaTool.JidoukaId, JidoukaTool.ToolId, Tool.ToolDescription], Foreign keys: [JidoukaTool.JidoukaId=Jidouka.JidoukaId, JidoukaTool.ToolId=Tool.ToolId], Possible cell values: ['machine learning']}",
     "Which departments are associated with these innovations?",
     "SELECT DISTINCT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE Tool.ToolDescription LIKE '%machine learning%';"],

    ["Which authors have created innovations with 'total jobs applied' over 50?",
     "SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE Jidouka.TotalJobApplied > 50;",
     "{Tables: [Author, Jidouka], Columns: [Author.AuthorName, Author.AuthorId, Jidouka.AuthorId, Jidouka.TotalJobApplied], Foreign keys: [Jidouka.AuthorId=Author.AuthorId], Possible cell values: [50]}",
     "What are the names of these innovations?",
     "SELECT Jidouka.ImprovementContent FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Jidouka.TotalJobApplied > 50;"],

    ["Which innovations were created by 'Author Y' in 'Department C'?",
     "SELECT Jidouka.ImprovementContent FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Author.AuthorName = 'Author Y' AND Department.DepartmentName = 'Department C';",
     "{Tables: [Jidouka, Author, Department], Columns: [Jidouka.ImprovementContent, Jidouka.AuthorId, Jidouka.DepartmentId, Author.AuthorId, Author.AuthorName, Department.DepartmentId, Department.DepartmentName], Foreign keys: [Jidouka.AuthorId=Author.AuthorId, Jidouka.DepartmentId=Department.DepartmentId], Possible cell values: ['Author Y', 'Department C']}",
     "Which tools were used in these innovations?",
     "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId JOIN Author ON Jidouka.AuthorId = Author.AuthorId JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Author.AuthorName = 'Author Y' AND Department.DepartmentName = 'Department C';"],

    # Not related to schema
    ["What is the distance between the Earth and the Sun?",
     "The average distance between the Earth and the Sun is about 93 million miles (150 million kilometers).",
     None,
     "What is the temperature of the Sun?",
     "The Sun's core temperature is about 15 million degrees Celsius."],

    ["Who discovered gravity?",
     "Gravity was discovered by Sir Isaac Newton.",
     None,
     "What is the law associated with gravity?",
     "Newton's Law of Universal Gravitation is associated with gravity."],

    ["What is the formula for the area of a circle?",
     "The formula for the area of a circle is πr², where r is the radius.",
     None,
     "What is the circumference formula?",
     "The formula for the circumference is 2πr, where r is the radius."],

    ["How many hours are in a day?",
     "There are 24 hours in a day.",
     None,
     "How many seconds are in an hour?",
     "There are 3600 seconds in an hour."],

    ["What is the tallest building in the world?",
     "The tallest building in the world is the Burj Khalifa in Dubai.",
     None,
     "How tall is it?",
     "The Burj Khalifa is approximately 828 meters (2,717 feet) tall."],

    ["Which innovations were created by 'Author Z' and saved more than 1000 hours?",
     "SELECT Jidouka.ImprovementContent FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName = 'Author Z' AND Jidouka.TotalTimeSaved > 1000;",
     "{Tables: [Jidouka, Author], Columns: [Jidouka.ImprovementContent, Jidouka.AuthorId, Jidouka.TotalTimeSaved, Author.AuthorId, Author.AuthorName], Foreign keys: [Jidouka.AuthorId=Author.AuthorId], Possible cell values: ['Author Z', 1000]}",
     "Which groups are associated with these innovations?",
     "SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName = 'Author Z' AND Jidouka.TotalTimeSaved > 1000;"],

    ["List all tools used in innovations created in 2021.",
     "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE YEAR(Jidouka.DateCreate) = 2021;",
     "{Tables: [Tool, JidoukaTool, Jidouka], Columns: [Tool.ToolName, Tool.ToolId, JidoukaTool.ToolId, JidoukaTool.JidoukaId, Jidouka.DateCreate], Foreign keys: [JidoukaTool.ToolId=Tool.ToolId, JidoukaTool.JidoukaId=Jidouka.JidoukaId], Possible cell values: [2021]}",
     "What were the total hours saved by these innovations?",
     "SELECT SUM(Jidouka.TotalTimeSaved) FROM Jidouka WHERE YEAR(DateCreate) = 2021;"],

    ["Which jobs are linked to 'Tool X'?",
     "SELECT DISTINCT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE Tool.ToolName = 'Tool X';",
     "{Tables: [Job, Jidouka, JidoukaTool, Tool], Columns: [Job.JobName, Job.JobId, Jidouka.JobId, Jidouka.JidoukaId, JidoukaTool.ToolId, Tool.ToolName], Foreign keys: [Jidouka.JobId=Job.JobId, JidoukaTool.JidoukaId=Jidouka.JidoukaId, JidoukaTool.ToolId=Tool.ToolId], Possible cell values: ['Tool X']}",
     "Which authors created these jobs?",
     "SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId JOIN Job ON Jidouka.JobId = Job.JobId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE Tool.ToolName = 'Tool X';"],

    ["Which departments contributed to innovations with 'Job A'?",
     "SELECT DISTINCT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId JOIN Job ON Jidouka.JobId = Job.JobId WHERE Job.JobName = 'Job A';",
     "{Tables: [Department, Jidouka, Job], Columns: [Department.DepartmentName, Department.DepartmentId, Jidouka.DepartmentId, Jidouka.JobId, Job.JobName], Foreign keys: [Jidouka.DepartmentId=Department.DepartmentId, Jidouka.JobId=Job.JobId], Possible cell values: ['Job A']}",
     "Which groups contributed to these innovations?",
     "SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId JOIN Job ON Jidouka.JobId = Job.JobId WHERE Job.JobName = 'Job A';"],

    ["List all innovations linked to tools with descriptions containing 'AI'.",
     "SELECT Jidouka.ImprovementContent FROM Jidouka JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE Tool.ToolDescription LIKE '%AI%';",
     "{Tables: [Jidouka, JidoukaTool, Tool], Columns: [Jidouka.ImprovementContent, Jidouka.JidoukaId, JidoukaTool.ToolId, Tool.ToolDescription], Foreign keys: [JidoukaTool.ToolId=Tool.ToolId, JidoukaTool.JidoukaId=Jidouka.JidoukaId], Possible cell values: ['AI']}",
     "What are the creation dates of these innovations?",
     "SELECT Jidouka.DateCreate FROM Jidouka JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE Tool.ToolDescription LIKE '%AI%';"],

    # Not related to schema
    ["What is the speed of light?",
     "The speed of light is approximately 299,792 kilometers per second (186,282 miles per second).",
     None,
     "What is the speed of sound?",
     "The speed of sound is approximately 343 meters per second (1,235 km/h) in air at room temperature."],

    ["Who painted the Mona Lisa?",
     "The Mona Lisa was painted by Leonardo da Vinci.",
     None,
     "Where is it displayed?",
     "The Mona Lisa is displayed in the Louvre Museum in Paris."],

    ["What is the smallest planet in the solar system?",
     "The smallest planet in the solar system is Mercury.",
     None,
     "What is the largest planet?",
     "The largest planet in the solar system is Jupiter."],

    ["What is the capital of Japan?",
     "The capital of Japan is Tokyo.",
     None,
     "What is the population of Tokyo?",
     "As of 2021, Tokyo's population is approximately 14 million."],

    ["Who wrote 'To Kill a Mockingbird'?",
     "'To Kill a Mockingbird' was written by Harper Lee.",
     None,
     "When was it published?",
     "It was published in 1960."],

    ["What is the total number of hours saved by innovations linked to the job 'Task A'?",
     "SELECT SUM(TotalTimeSaved) FROM Jidouka WHERE JobName LIKE LOWER('%Task A%');",
     "{Tables: [Jidouka], Columns: [Jidouka.TotalTimeSaved, Jidouka.JobName], Foreign keys: [], Possible cell values: [Task A]}",
     "What innovations were linked to this job?",
     "SELECT ImprovementContent FROM Jidouka WHERE JobName LIKE LOWER('%Task A%');"],

    ["Which tools were used in the innovations related to job 'Task B'?",
     "SELECT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.JobName LIKE LOWER('%Task B%');",
     "{Tables: [Tool, JidoukaTool, Jidouka], Columns: [Tool.ToolName, Jidouka.JobName], Foreign keys: [JidoukaTool.JidoukaId=Jidouka.JidoukaId, JidoukaTool.ToolId=Tool.ToolId], Possible cell values: [Task B]}",
     "Who created the innovations linked to this job?",
     "SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE Jidouka.JobName LIKE LOWER('%Task B%');"],

    ["List all employees who worked on the job 'Task C'.",
     "SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE Jidouka.JobName LIKE LOWER('%Task C%');",
     "{Tables: [Author, Jidouka], Columns: [Author.AuthorName, Jidouka.JobName], Foreign keys: [Jidouka.AuthorId=Author.AuthorId], Possible cell values: [Task C]}",
     "Which departments were involved in this job?",
     "SELECT DISTINCT Department.DepartmentName FROM Department JOIN Jidouka ON Jidouka.DepartmentId = Department.DepartmentId WHERE Jidouka.JobName LIKE LOWER('%Task C%');"],

    ["What is the total number of jobs that applied innovation ID 456?",
     "SELECT TotalJobApplied FROM Jidouka WHERE JidoukaId = 456;",
     "{Tables: [Jidouka], Columns: [Jidouka.TotalJobApplied, Jidouka.JidoukaId], Foreign keys: [], Possible cell values: [456]}",
     "What are the details of the innovation with ID 456?",
     "SELECT Description FROM Jidouka WHERE JidoukaId = 456;"],

    ["What improvements have been made by the department 'Design Center X'?",
     "SELECT ImprovementContent FROM Jidouka JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName LIKE 'Design Center X';",
     "{Tables: [Jidouka, Department], Columns: [Jidouka.ImprovementContent, Department.DepartmentName], Foreign keys: [Jidouka.DepartmentId=Department.DepartmentId], Possible cell values: [Design Center X]}",
     "What job types were involved in these improvements?",
     "SELECT DISTINCT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.DepartmentId IN (SELECT DepartmentId FROM Department WHERE DepartmentName LIKE 'Design Center X');"],

    ["Which tools are associated with innovation ID 789?",
     "SELECT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId WHERE JidoukaTool.JidoukaId = 789;",
     "{Tables: [Tool, JidoukaTool], Columns: [Tool.ToolName, JidoukaTool.JidoukaId], Foreign keys: [JidoukaTool.ToolId=Tool.ToolId], Possible cell values: [789]}",
     "Which authors contributed to this innovation?",
     "SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE Jidouka.JidoukaId = 789;"],

    ["Which teams are linked to the job 'Task D'?",
     "SELECT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId WHERE Jidouka.JobName LIKE LOWER('%Task D%');",
     "{Tables: [GroupDC, Jidouka], Columns: [GroupDC.GroupDCName, Jidouka.JobName], Foreign keys: [Jidouka.GroupDCId=GroupDC.GroupDCId], Possible cell values: [Task D]}",
     "Which tools were used in these innovations?",
     "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.JobName LIKE LOWER('%Task D%');"],

    ["List all the improvements made by author 'John Doe'.",
     "SELECT ImprovementContent FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName = 'John Doe';",
     "{Tables: [Jidouka, Author], Columns: [Jidouka.ImprovementContent, Author.AuthorName], Foreign keys: [Jidouka.AuthorId=Author.AuthorId], Possible cell values: ['John Doe']}",
     "What job types were linked to these innovations?",
     "SELECT DISTINCT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.AuthorId = (SELECT AuthorId FROM Author WHERE AuthorName = 'John Doe');"],

    ["What is the total number of hours saved by improvements in the 'Design Center Y'?",
     "SELECT SUM(TotalTimeSaved) FROM Jidouka JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName = 'Design Center Y';",
     "{Tables: [Jidouka, Department], Columns: [Jidouka.TotalTimeSaved, Department.DepartmentName], Foreign keys: [Jidouka.DepartmentId=Department.DepartmentId], Possible cell values: ['Design Center Y']}",
     "What improvements contributed to these hours saved?",
     "SELECT ImprovementContent FROM Jidouka WHERE DepartmentId IN (SELECT DepartmentId FROM Department WHERE DepartmentName = 'Design Center Y');"],

    ["Which improvements were applied to the product 'Product Z'?",
     "SELECT ImprovementContent FROM Jidouka WHERE ProductApply LIKE 'Product Z';",
     "{Tables: [Jidouka], Columns: [Jidouka.ImprovementContent, Jidouka.ProductApply], Foreign keys: [], Possible cell values: ['Product Z']}",
     "Which jobs were associated with these improvements?",
     "SELECT DISTINCT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.ProductApply LIKE 'Product Z';"],

    ["What job types were associated with innovation ID 101?",
     "SELECT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.JidoukaId = 101;",
     "{Tables: [Job, Jidouka], Columns: [Job.JobName, Jidouka.JidoukaId], Foreign keys: [Jidouka.JobId=Job.JobId], Possible cell values: [101]}",
     "Which departments were linked to these job types?",
     "SELECT DISTINCT Department.DepartmentName FROM Department JOIN Jidouka ON Department.DepartmentId = Jidouka.DepartmentId WHERE Jidouka.JidoukaId = 101;"],

    ["How many employees worked on the job 'Task E'?",
     "SELECT COUNT(DISTINCT Author.AuthorName) FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE Jidouka.JobName LIKE LOWER('%Task E%');",
     "{Tables: [Author, Jidouka], Columns: [Author.AuthorName, Jidouka.JobName], Foreign keys: [Jidouka.AuthorId=Author.AuthorId], Possible cell values: [Task E]}",
     "What innovations did these employees contribute to?",
     "SELECT DISTINCT ImprovementContent FROM Jidouka WHERE JobName LIKE LOWER('%Task E%');"],

    ["What are the details of innovation ID 202?",
     "SELECT Description FROM Jidouka WHERE JidoukaId = 202;",
     "{Tables: [Jidouka], Columns: [Jidouka.Description, Jidouka.JidoukaId], Foreign keys: [], Possible cell values: [202]}",
     "What tools were used in this innovation?",
     "SELECT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId WHERE JidoukaTool.JidoukaId = 202;"],

    ["Which innovations were released after '2022-01-01'?",
     "SELECT ImprovementContent FROM Jidouka WHERE DateCreate > '2022-01-01';",
     "{Tables: [Jidouka], Columns: [Jidouka.ImprovementContent, Jidouka.DateCreate], Foreign keys: [], Possible cell values: ['2022-01-01']}",
     "Which tools were used in these innovations?",
     "SELECT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId WHERE Jidouka.DateCreate > '2022-01-01';"],

    ["What improvements have been made by author 'Jane Smith'?",
     "SELECT ImprovementContent FROM Jidouka JOIN Author ON Jidouka.AuthorId = Author.AuthorId WHERE Author.AuthorName = 'Jane Smith';",
     "{Tables: [Jidouka, Author], Columns: [Jidouka.ImprovementContent, Author.AuthorName], Foreign keys: [Jidouka.AuthorId=Author.AuthorId], Possible cell values: ['Jane Smith']}",
     "What job types were linked to these improvements?",
     "SELECT DISTINCT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId WHERE Jidouka.AuthorId = (SELECT AuthorId FROM Author WHERE AuthorName = 'Jane Smith');"],

    ["What is the total number of jobs that applied innovation ID 333?",
     "SELECT TotalJobApplied FROM Jidouka WHERE JidoukaId = 333;",
     "{Tables: [Jidouka], Columns: [Jidouka.TotalJobApplied, Jidouka.JidoukaId], Foreign keys: [], Possible cell values: [333]}",
     "What is the improvement content of this innovation?",
     "SELECT ImprovementContent FROM Jidouka WHERE JidoukaId = 333;"],

    ["Which innovations are associated with 'Department Alpha'?",
     "SELECT Jidouka.ImprovementContent FROM Jidouka JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName = 'Department Alpha';",
     "{Tables: [Jidouka, Department], Columns: [Jidouka.ImprovementContent, Jidouka.DepartmentId, Department.DepartmentId, Department.DepartmentName], Foreign keys: [Jidouka.DepartmentId=Department.DepartmentId], Possible cell values: ['Department Alpha']}",
     "What is the total saved time for these innovations?",
     "SELECT SUM(Jidouka.TotalTimeSaved) FROM Jidouka JOIN Department ON Jidouka.DepartmentId = Department.DepartmentId WHERE Department.DepartmentName = 'Department Alpha';"],

    ["List all innovations launched in 2023.",
     "SELECT Jidouka.ImprovementContent FROM Jidouka WHERE YEAR(Jidouka.DateCreate) = 2023;",
     "{Tables: [Jidouka], Columns: [Jidouka.ImprovementContent, Jidouka.DateCreate], Foreign keys: [], Possible cell values: [2023]}",
     "Which authors contributed to these innovations?",
     "SELECT DISTINCT Author.AuthorName FROM Author JOIN Jidouka ON Author.AuthorId = Jidouka.AuthorId WHERE YEAR(Jidouka.DateCreate) = 2023;"],

    ["Which tools are used by 'Group Gamma'?",
     "SELECT DISTINCT Tool.ToolName FROM Tool JOIN JidoukaTool ON Tool.ToolId = JidoukaTool.ToolId JOIN Jidouka ON JidoukaTool.JidoukaId = Jidouka.JidoukaId JOIN GroupDC ON Jidouka.GroupDCId = GroupDC.GroupDCId WHERE GroupDC.GroupDCName = 'Group Gamma';",
     "{Tables: [Tool, JidoukaTool, Jidouka, GroupDC], Columns: [Tool.ToolName, Tool.ToolId, JidoukaTool.ToolId, JidoukaTool.JidoukaId, GroupDC.GroupDCName, Jidouka.GroupDCId], Foreign keys: [JidoukaTool.ToolId=Tool.ToolId, JidoukaTool.JidoukaId=Jidouka.JidoukaId, Jidouka.GroupDCId=GroupDC.GroupDCId], Possible cell values: ['Group Gamma']}",
     "What is the total number of jobs these innovations are applied to?",
     "SELECT SUM(Jidouka.TotalJobApplied) FROM Jidouka JOIN GroupDC ON Jidouka.GroupDCId = GroupDC.GroupDCId WHERE GroupDC.GroupDCName = 'Group Gamma';"],

    ["Which innovations use tools with names starting with 'Auto'?",
     "SELECT Jidouka.ImprovementContent FROM Jidouka JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE Tool.ToolName LIKE 'Auto%';",
     "{Tables: [Jidouka, JidoukaTool, Tool], Columns: [Jidouka.ImprovementContent, Jidouka.JidoukaId, JidoukaTool.ToolId, Tool.ToolName], Foreign keys: [JidoukaTool.JidoukaId=Jidouka.JidoukaId, JidoukaTool.ToolId=Tool.ToolId], Possible cell values: ['Auto%']}",
     "Which jobs are linked to these innovations?",
     "SELECT DISTINCT Job.JobName FROM Job JOIN Jidouka ON Job.JobId = Jidouka.JobId JOIN JidoukaTool ON Jidouka.JidoukaId = JidoukaTool.JidoukaId JOIN Tool ON JidoukaTool.ToolId = Tool.ToolId WHERE Tool.ToolName LIKE 'Auto%';"],

    ["List all groups involved in innovations with over 500 jobs applied.",
     "SELECT DISTINCT GroupDC.GroupDCName FROM GroupDC JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId WHERE Jidouka.TotalJobApplied > 500;",
     "{Tables: [GroupDC, Jidouka], Columns: [GroupDC.GroupDCName, GroupDC.GroupDCId, Jidouka.TotalJobApplied, Jidouka.GroupDCId], Foreign keys: [Jidouka.GroupDCId=GroupDC.GroupDCId], Possible cell values: [500]}",
     "Which departments do these groups belong to?",
     "SELECT DISTINCT Department.DepartmentName FROM Department JOIN GroupDC ON Department.DepartmentId = GroupDC.DepartmentId JOIN Jidouka ON GroupDC.GroupDCId = Jidouka.GroupDCId WHERE Jidouka.TotalJobApplied > 500;"],

    # Not related to schema
    ["What is the boiling point of water?",
     "The boiling point of water is 100°C (212°F) at sea level.",
     None,
     "What is the freezing point of water?",
     "The freezing point of water is 0°C (32°F)."],

    ["Who discovered penicillin?",
     "Penicillin was discovered by Alexander Fleming in 1928.",
     None,
     "What is penicillin used for?",
     "Penicillin is an antibiotic used to treat bacterial infections."],

    ["What is the largest desert in the world?",
     "The largest desert in the world is the Antarctic Desert.",
     None,
     "What is the largest hot desert?",
     "The largest hot desert in the world is the Sahara Desert."],

    ["How many continents are there on Earth?",
     "There are seven continents on Earth.",
     None,
     "Which is the smallest continent?",
     "The smallest continent is Australia."],

    ["Who wrote the play 'Romeo and Juliet'?",
     "'Romeo and Juliet' was written by William Shakespeare.",
     None,
     "When was it first performed?",
     "It was first performed in 1597."],

]

In [18]:
len(data)

146

In [19]:
import re
def modify_query(query):
    modified_query = re.sub(r"= '([^']*)'", r"LIKE LOWER('%\1%')", query)
    return modified_query

In [20]:
data2 = []
for i in range(len(data)):
    lst = []
    lst.append(data[i][0])
    lst.append(modify_query(data[i][1]))
    lst.append(data[i][2])
    lst.append(data[i][3])
    lst.append(modify_query(data[i][4]))
    data2.append(lst)

In [22]:
dct = {'previous_question':[], 'previous_answer':[], 'schema_linking':[], 'question':[], 'answer':[]}
for i in range(len(data2)):
    dct['previous_question'].append(data[i][0])
    dct['previous_answer'].append(data2[i][1])
    dct['schema_linking'].append(data2[i][2])
    dct['question'].append(data2[i][3])
    dct['answer'].append(data2[i][4])

In [23]:
import pandas as pd 
df3 = pd.DataFrame(dct)

In [24]:
len(df3)

146

In [25]:
df3.to_csv('output146_records_contextAware.csv', index=False)